export const RALLY_CONFIG = {
  track: {
    segments: 192,
    // Hover racing needs room for continuous strafe lines and readable
    // pickup/obstacle choices.  Track definitions may override this per
    // section, but this remains the shared physics/rendering baseline.
    width: 16,
    radiusX: 28,
    radiusZ: 52,
    centerZ: 70,
    terrainStep: 4,
    terrainMinX: -190,
    terrainMaxX: 190,
    terrainMinZ: -60,
    terrainMaxZ: 320,
    // Keep a caller's local segment hint through wide off-road/self-crossing
    // sections. Full-track fallback is reserved for real teleports or a
    // position that is well outside the hinted corridor.
    queryFallbackDistance: 24,
    roadVisualEpsilon: 0.035,
    terrainVisualEpsilon: 0.03,
    shoulderWidthRatio: 0.18,
    gravelHalfWidthRatio: 1.35,
    scenerySafetyMargin: 3,
    protectedGateClearance: 42,
  },
  vehicle: {
    maxSpeed: 40,
    reverseSpeed: 7,
    height: 0.62,
    acceleration: 21.5,
    brakeAcceleration: 30,
    poweredRollingResistance: 0.42,
    coastingRollingResistance: 2.8,
    aerodynamicDrag: 0.009,
    offRoadSpeedRatio: 0.62,
    offRoadDrag: 3.2,
    gravelSpeedRatio: 0.82,
    gravelDrag: 1.4,
    gravelLateralGrip: 5.8,
    lateralGrip: 8.5,
    offRoadLateralGrip: 4.8,
    steeringRateLowSpeed: 2.1,
    steeringRateHighSpeed: 0.92,
    steeringSlipForce: 0.14,
    reverseAcceleration: 7.5,
    bodyWidth: 1.8,
    bodyLength: 2.8,
    gravity: 26,
    suspensionSpring: 18,
    suspensionDamping: 24,
    takeoffGap: 0.42,
    landingTolerance: 0.18,
    wheelContactTolerance: 0.24,
    wheelMaxSuspensionGap: 0.9,
    recoveryStuckSeconds: 3,
    recoveryMinX: -180,
    recoveryMaxX: 180,
    recoveryMinZ: -150,
    // Cart Rogue's authored run extends through the boss arena at z=476.
    // Keep the shared finite-position guard beyond that world instead of
    // treating Arena 03's center at z=280 as the old rally recovery edge.
    recoveryMaxZ: 520,
    recoveryMinY: -24,
    recoveryMaxY: 90,
    driftMinSpeed: 7.5,
    driftGrip: 4.6,
    grassDriftGrip: 3.6,
    driftSlipForce: 0.24,
    driftBrakeRatio: 0.34,
    driftRecoveryGrip: 3.8,
    collisionSpeedRatio: 0.34,
    shortcutBreakSpeed: 9,
    shortcutBreakSpeedRatio: 0.78,
    hoverHeight: 0.86,
    hoverLateralAcceleration: 54,
    hoverLateralDeceleration: 72,
    hoverLateralDrag: 8.5,
    hoverLateralPositionGain: 4.6,
    hoverBoundaryRecoveryGain: 36,
    hoverMaxStrafeSpeed: 17,
    hoverRoadFollowRate: 9.5,
    hoverBoundaryMargin: 0.42,
    initialBoostCharges: 2,
    maxBoostCharges: 4,
    boostDuration: 1.85,
    boostMaxAccumulatedTime: 5.2,
    boostChainWindow: 1.1,
    boostSpeedKick: 4.5,
    boostChargePickupRadius: 1.45,
  },
  race: {
    countdownSeconds: 3.2,
    minimumLapSeconds: 5,
    wrongWaySpeed: 2.2,
    gateLateralTolerance: 0.82,
    medalThresholds: { bronze: 45, silver: 36, gold: 30 },
  },
} as const;

export type RallyConfig = typeof RALLY_CONFIG;
