from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"missing anchor: {label}")
    return text.replace(old, new, 1)


def update(path: str, transform) -> None:
    target = Path(path)
    before = target.read_text()
    after = transform(before)
    if before == after:
        raise SystemExit(f"no changes made: {path}")
    target.write_text(after)


def patch_rules(source: str) -> str:
    anchor = '''export type SkyDancerSkyRaidRank = "C" | "B" | "A" | "S" | "S+";\n'''
    insert = '''export interface SkyDancerSkyRaidFlightProfile {\n  label: "OPEN SKY" | "CANYON KNIFE" | "VERTICAL HUNT" | "STORM WEAVE" | "SIEGE WEIGHT";\n  verticalSpeedScale: number;\n  bankScale: number;\n  bankResponseScale: number;\n  pitchScale: number;\n  speedScale: number;\n  handlingScale: number;\n}\n\nconst SKY_DANCER_SKY_RAID_FLIGHT_PROFILES: Readonly<Record<SkyDancerSkyRaidActId, SkyDancerSkyRaidFlightProfile>> = {\n  "dawn-city": { label: "OPEN SKY", verticalSpeedScale: 1.00, bankScale: 0.94, bankResponseScale: 0.96, pitchScale: 0.96, speedScale: 0.98, handlingScale: 1.00 },\n  "red-canyon": { label: "CANYON KNIFE", verticalSpeedScale: 0.84, bankScale: 1.16, bankResponseScale: 1.14, pitchScale: 0.92, speedScale: 1.04, handlingScale: 1.14 },\n  "cloud-fleet": { label: "VERTICAL HUNT", verticalSpeedScale: 1.20, bankScale: 0.92, bankResponseScale: 0.92, pitchScale: 1.12, speedScale: 1.00, handlingScale: 0.98 },\n  "storm-carrier": { label: "STORM WEAVE", verticalSpeedScale: 1.12, bankScale: 1.12, bankResponseScale: 1.16, pitchScale: 1.08, speedScale: 1.07, handlingScale: 1.10 },\n  "prism-citadel": { label: "SIEGE WEIGHT", verticalSpeedScale: 0.94, bankScale: 0.86, bankResponseScale: 0.88, pitchScale: 0.94, speedScale: 0.97, handlingScale: 0.92 },\n};\n\nexport function skyDancerSkyRaidFlightProfile(actId: SkyDancerSkyRaidActId): SkyDancerSkyRaidFlightProfile {\n  return SKY_DANCER_SKY_RAID_FLIGHT_PROFILES[actId];\n}\n\nexport function skyDancerSkyRaidBossSupportTargetCount(elapsedSeconds: number, baseCount: number): number {\n  return elapsedSeconds >= SKY_DANCER_SKY_RAID_BOSS_TRIGGER_SECONDS ? Math.min(8, baseCount + 1) : baseCount;\n}\n\nexport type SkyDancerSkyRaidRank = "C" | "B" | "A" | "S" | "S+";\n'''
    return replace_once(source, anchor, insert, "flight profiles")


def patch_flight(source: str) -> str:
    source = replace_once(source, '''export interface SkyDancerSkyRaidFlightSnapshot {\n  altitude: number;\n  verticalSpeed: number;\n  bank: number;\n  pitch: number;\n  turnRate: number;\n}\n''', '''export interface SkyDancerSkyRaidFlightSnapshot {\n  altitude: number;\n  verticalSpeed: number;\n  bank: number;\n  pitch: number;\n  turnRate: number;\n}\n\nexport interface SkyDancerSkyRaidFlightTuning {\n  verticalSpeedScale: number;\n  bankScale: number;\n  bankResponseScale: number;\n  pitchScale: number;\n}\n\nconst DEFAULT_SKY_RAID_FLIGHT_TUNING: SkyDancerSkyRaidFlightTuning = {\n  verticalSpeedScale: 1,\n  bankScale: 1,\n  bankResponseScale: 1,\n  pitchScale: 1,\n};\n''', "flight tuning interface")
    source = replace_once(source, '''  private previousHeading: number | null = null;\n\n  setVerticalInput(value: number): void {\n''', '''  private previousHeading: number | null = null;\n  private tuning: SkyDancerSkyRaidFlightTuning = { ...DEFAULT_SKY_RAID_FLIGHT_TUNING };\n\n  setTuning(tuning: SkyDancerSkyRaidFlightTuning): void {\n    this.tuning = {\n      verticalSpeedScale: clamp(tuning.verticalSpeedScale, 0.72, 1.35),\n      bankScale: clamp(tuning.bankScale, 0.72, 1.28),\n      bankResponseScale: clamp(tuning.bankResponseScale, 0.72, 1.32),\n      pitchScale: clamp(tuning.pitchScale, 0.72, 1.28),\n    };\n  }\n\n  setVerticalInput(value: number): void {\n''', "flight set tuning")
    source = replace_once(source, '''    const maxVerticalSpeed = boost ? 22 : 16;\n    const targetVerticalSpeed = this.verticalInput * maxVerticalSpeed;\n''', '''    const maxVerticalSpeed = (boost ? 22 : 16) * this.tuning.verticalSpeedScale;\n    const targetVerticalSpeed = this.verticalInput * maxVerticalSpeed;\n''', "vertical scale")
    source = replace_once(source, '''    const targetBank = skyRaidBankTarget(turnRate, steer);\n    const bankResponse = Math.abs(targetBank) > Math.abs(this.bank) ? 7.8 : 4.2;\n    this.bank = damp(this.bank, targetBank, bankResponse, dt);\n    const targetPitch = skyRaidPitchTarget(this.verticalSpeed, this.verticalInput, maxVerticalSpeed);\n    this.pitch = damp(this.pitch, targetPitch, 6.2, dt);\n''', '''    const targetBank = clamp(\n      skyRaidBankTarget(turnRate, steer) * this.tuning.bankScale,\n      -SKY_RAID_MAX_BANK,\n      SKY_RAID_MAX_BANK,\n    );\n    const bankResponse = (Math.abs(targetBank) > Math.abs(this.bank) ? 7.8 : 4.2) * this.tuning.bankResponseScale;\n    this.bank = damp(this.bank, targetBank, bankResponse, dt);\n    const targetPitch = clamp(\n      skyRaidPitchTarget(this.verticalSpeed, this.verticalInput, maxVerticalSpeed) * this.tuning.pitchScale,\n      -SKY_RAID_MAX_PITCH,\n      SKY_RAID_MAX_PITCH,\n    );\n    this.pitch = damp(this.pitch, targetPitch, 6.2, dt);\n''', "bank pitch scale")
    return source


def patch_raid(source: str) -> str:
    source = replace_once(source, '''  skyDancerSkyRaidEnemyDoctrine,\n  skyDancerSkyRaidKillScore,\n''', '''  skyDancerSkyRaidEnemyDoctrine,\n  skyDancerSkyRaidFlightProfile,\n  skyDancerSkyRaidBossSupportTargetCount,\n  skyDancerSkyRaidKillScore,\n''', "raid imports")
    source = replace_once(source, '''  speedFx: THREE.Group;\n  speedMaterial: THREE.MeshBasicMaterial;\n  speedColor: THREE.Color;\n''', '''  speedFx: THREE.Group;\n  speedMaterial: THREE.MeshBasicMaterial;\n  speedColor: THREE.Color;\n  rushFx: THREE.Group;\n  rushMaterial: THREE.MeshBasicMaterial;\n  rushBurst: number;\n  lastRushActive: boolean;\n  lastPerfectRushes: number;\n''', "visual state rush fields")
    source = replace_once(source, '''    targetCount: rush ? profile.rushTargetCount : profile.baseTargetCount,\n    correctionSpeed: rush ? profile.rushCorrectionSpeed : profile.correctionSpeed,\n''', '''    targetCount: elapsedSeconds >= SKY_DANCER_SKY_RAID_BOSS_TRIGGER_SECONDS\n      ? Math.min(5, profile.rushTargetCount + 1)\n      : rush ? profile.rushTargetCount : profile.baseTargetCount,\n    correctionSpeed: elapsedSeconds >= SKY_DANCER_SKY_RAID_BOSS_TRIGGER_SECONDS\n      ? profile.rushCorrectionSpeed * 1.10\n      : rush ? profile.rushCorrectionSpeed : profile.correctionSpeed,\n''', "boss formation pressure")
    source = replace_once(source, '''function stepSkyRaidFlight(demo: RaidWebGLDemo, delta: number): SkyDancerSkyRaidFlightSnapshot {\n  const car = demo.session.car;\n  const flight = flightControllerFor(demo).step(delta, car.heading, demo.steer, car.boostActive);\n''', '''function stepSkyRaidFlight(demo: RaidWebGLDemo, delta: number): SkyDancerSkyRaidFlightSnapshot {\n  const car = demo.session.car;\n  const hunt = getCartTurboHuntSnapshot(demo.session);\n  const profile = skyDancerSkyRaidFlightProfile(skyDancerSkyRaidActFor(hunt?.huntElapsedSeconds ?? 0).id);\n  const controller = flightControllerFor(demo);\n  controller.setTuning(profile);\n  const flight = controller.step(delta, car.heading, demo.steer, car.boostActive);\n  demo.scene.userData.skyRaidFlightProfile = profile.label;\n''', "apply flight profile")
    source = replace_once(source, '''  const pressure = skyDancerSkyRaidPressure(hunt.huntElapsedSeconds);\n  session.car.definition.maxSpeed = Math.max(state.baseMaxSpeed, 23.5 + pressure * 3.1);\n  session.car.definition.handling = state.baseHandling * (1 + pressure * 0.08);\n''', '''  const pressure = skyDancerSkyRaidPressure(hunt.huntElapsedSeconds);\n  const flightProfile = skyDancerSkyRaidFlightProfile(act.id);\n  session.car.definition.maxSpeed = Math.max(state.baseMaxSpeed, (23.5 + pressure * 3.1) * flightProfile.speedScale);\n  session.car.definition.handling = state.baseHandling * (1 + pressure * 0.08) * flightProfile.handlingScale;\n''', "act drive identity")
    source = replace_once(source, '''function buildRaidVisuals(demo: RaidWebGLDemo): void {\n''', '''function buildRushFx(): THREE.Group {\n  const root = new THREE.Group();\n  const rushMaterial = new THREE.MeshBasicMaterial({\n    color: 0xbdf8ff,\n    transparent: true,\n    opacity: 0,\n    depthTest: false,\n    depthWrite: false,\n    blending: THREE.AdditiveBlending,\n    toneMapped: false,\n  });\n  for (let index = 0; index < 3; index += 1) {\n    const ring = new THREE.Mesh(new THREE.TorusGeometry(2.4 + index * 1.8, 0.075 + index * 0.015, 6, 32), rushMaterial);\n    ring.rotation.x = Math.PI / 2;\n    ring.position.z = 5.5 + index * 2.2;\n    ring.renderOrder = 1090;\n    root.add(ring);\n  }\n  root.visible = false;\n  return root;\n}\n\nfunction buildRaidVisuals(demo: RaidWebGLDemo): void {\n''', "rush fx builder")
    source = replace_once(source, '''  const speedMaterial = (speedFx.children[0] as THREE.Mesh).material as THREE.MeshBasicMaterial;\n  demo.scene.add(root, speedFx);\n''', '''  const speedMaterial = (speedFx.children[0] as THREE.Mesh).material as THREE.MeshBasicMaterial;\n  const rushFx = buildRushFx();\n  rushFx.name = "sky-raid-rush-fx";\n  const rushMaterial = (rushFx.children[0] as THREE.Mesh).material as THREE.MeshBasicMaterial;\n  demo.scene.add(root, speedFx, rushFx);\n''', "add rush fx")
    source = replace_once(source, '''    speedColor: new THREE.Color(SKY_DANCER_SKY_RAID_ACTS[0].palette.accent),\n    attackTelegraphs: new Map(),\n''', '''    speedColor: new THREE.Color(SKY_DANCER_SKY_RAID_ACTS[0].palette.accent),\n    rushFx,\n    rushMaterial,\n    rushBurst: 0,\n    lastRushActive: false,\n    lastPerfectRushes: 0,\n    attackTelegraphs: new Map(),\n''', "rush visual state init")
    source = replace_once(source, '''    visual.root.visible = false;\n    visual.speedFx.visible = false;\n    restoreSkyRaidEnemySilhouetteAssist(demo);\n''', '''    visual.root.visible = false;\n    visual.speedFx.visible = false;\n    visual.rushFx.visible = false;\n    restoreSkyRaidEnemySilhouetteAssist(demo);\n''', "hide rush fx")
    source = replace_once(source, '''  const rushFx = raid.rushActive ? 1 : 0;\n  const speedFxIntensity = clamp(cruiseFx * 0.22 + rushFx * 0.32 + turboFx * 0.72, 0, 1);\n''', '''  const rushFx = raid.rushActive ? 1 : 0;\n  if (raid.rushActive && !visual.lastRushActive) visual.rushBurst = Math.max(visual.rushBurst, 1);\n  if (raid.perfectRushes > visual.lastPerfectRushes) visual.rushBurst = Math.max(visual.rushBurst, 1.35);\n  visual.lastRushActive = raid.rushActive;\n  visual.lastPerfectRushes = raid.perfectRushes;\n  visual.rushBurst = Math.max(0, visual.rushBurst - Math.min(delta, 0.05) * 1.28);\n  const rushVisual = clamp((raid.rushActive ? 0.52 : 0) + visual.rushBurst, 0, 1.35);\n  visual.rushFx.visible = rushVisual > 0.035;\n  visual.rushFx.position.set(playerX, 1.8 + resolvedFlight.altitude, playerZ);\n  visual.rushFx.rotation.y = playerHeading;\n  visual.rushMaterial.color.setHex(raid.palette.accent);\n  visual.rushMaterial.opacity = clamp(0.08 + rushVisual * 0.24, 0, 0.40);\n  for (let index = 0; index < visual.rushFx.children.length; index += 1) {\n    const ring = visual.rushFx.children[index];\n    const pulse = 1 + Math.sin(raid.elapsedSeconds * 11 + index * 1.7) * 0.055;\n    const burstScale = 1 + visual.rushBurst * (0.20 + index * 0.06);\n    ring.scale.setScalar(pulse * burstScale);\n    ring.position.z = 5.5 + index * 2.2 + (raid.elapsedSeconds * (7 + index * 1.4)) % 5.5;\n  }\n  demo.scene.userData.skyRaidRushFxIntensity = rushVisual;\n  const speedFxIntensity = clamp(cruiseFx * 0.22 + rushFx * 0.32 + turboFx * 0.72, 0, 1);\n''', "rush fx update")
    source = replace_once(source, '''      rushActive: raid.rushActive,\n      flightSpeed,\n''', '''      rushActive: raid.rushActive,\n      rushFxIntensity: Number(demo.scene.userData.skyRaidRushFxIntensity ?? 0),\n      flightProfile: String(demo.scene.userData.skyRaidFlightProfile ?? ""),\n      flightSpeed,\n''', "speed polish diagnostics")
    source = replace_once(source, '''    return skyDancerSkyRaidEnemyDoctrine(skyDancerSkyRaidActFor(context.elapsedSeconds).id).activeTargetCount;\n''', '''    const baseCount = skyDancerSkyRaidEnemyDoctrine(skyDancerSkyRaidActFor(context.elapsedSeconds).id).activeTargetCount;\n    return skyDancerSkyRaidBossSupportTargetCount(context.elapsedSeconds, baseCount);\n''', "boss support resolver")
    source = replace_once(source, '''  const cruiseFov = clamp((speed - 18) * 0.10, 0, 2.2);\n  const targetFov = clamp(\n    cameraFx.baseFov + cruiseFov + turboCamera * (6.6 + turbo.releaseCharge * 3.4) + cameraFx.shotKick * 0.35 - cameraFx.hitKick * 0.75,\n''', '''  const cruiseFov = clamp((speed - 18) * 0.10, 0, 2.2);\n  const rushCamera = latestSkyRaidSnapshot?.rushActive ? 1 : 0;\n  const titanCamera = latestSkyRaidSnapshot?.bossForced ? 1 : 0;\n  const targetFov = clamp(\n    cameraFx.baseFov + cruiseFov + rushCamera * 1.8 + titanCamera * 0.75 + turboCamera * (6.6 + turbo.releaseCharge * 3.4) + cameraFx.shotKick * 0.35 - cameraFx.hitKick * 0.75,\n''', "rush titan fov")
    source = replace_once(source, '''  this.scene.userData.skyRaidCameraCruiseFov = cruiseFov;\n''', '''  this.scene.userData.skyRaidCameraCruiseFov = cruiseFov;\n  this.scene.userData.skyRaidCameraRushBlend = rushCamera;\n  this.scene.userData.skyRaidCameraTitanBlend = titanCamera;\n''', "camera diagnostics")
    return source


def patch_tests(source: str) -> str:
    source = replace_once(source, '''  skyDancerSkyRaidEnemyDoctrine,\n  skyDancerSkyRaidEnemySpawnPriority,\n''', '''  skyDancerSkyRaidEnemyDoctrine,\n  skyDancerSkyRaidEnemySpawnPriority,\n  skyDancerSkyRaidFlightProfile,\n  skyDancerSkyRaidBossSupportTargetCount,\n''', "test imports")
    append = '''\n\ntest("SKY RAID gives each act a distinct flight identity instead of only recoloring the world", () => {\n  const profiles = SKY_DANCER_SKY_RAID_ACTS.map((act) => skyDancerSkyRaidFlightProfile(act.id));\n  assert.deepEqual(profiles.map((profile) => profile.label), [\n    "OPEN SKY",\n    "CANYON KNIFE",\n    "VERTICAL HUNT",\n    "STORM WEAVE",\n    "SIEGE WEIGHT",\n  ]);\n  assert.ok(profiles[1].bankScale > profiles[0].bankScale);\n  assert.ok(profiles[1].handlingScale > profiles[0].handlingScale);\n  assert.ok(profiles[2].verticalSpeedScale > profiles[0].verticalSpeedScale);\n  assert.ok(profiles[3].speedScale > profiles[0].speedScale);\n  assert.ok(profiles[4].handlingScale < profiles[0].handlingScale);\n  const flightSource = readFileSync(new URL("../src/sky/SkyDancerSkyRaidFlight.ts", import.meta.url), "utf8");\n  const raidSource = readFileSync(new URL("../src/sky/SkyDancerSkyRaid.ts", import.meta.url), "utf8");\n  assert.match(flightSource, /setTuning\(tuning: SkyDancerSkyRaidFlightTuning\)/);\n  assert.match(raidSource, /controller\.setTuning\(profile\)/);\n  assert.match(raidSource, /flightProfile\.handlingScale/);\n});\n\ntest("SKY RAID escalates Titan into a supported siege without flooding the phone screen", () => {\n  assert.equal(skyDancerSkyRaidBossSupportTargetCount(SKY_DANCER_SKY_RAID_BOSS_TRIGGER_SECONDS - 0.01, 7), 7);\n  assert.equal(skyDancerSkyRaidBossSupportTargetCount(SKY_DANCER_SKY_RAID_BOSS_TRIGGER_SECONDS, 7), 8);\n  assert.equal(skyDancerSkyRaidBossSupportTargetCount(SKY_DANCER_SKY_RAID_BOSS_TRIGGER_SECONDS + 20, 8), 8);\n  const raidSource = readFileSync(new URL("../src/sky/SkyDancerSkyRaid.ts", import.meta.url), "utf8");\n  assert.match(raidSource, /Math\.min\(5, profile\.rushTargetCount \+ 1\)/);\n  assert.match(raidSource, /profile\.rushCorrectionSpeed \* 1\.10/);\n  assert.match(raidSource, /skyDancerSkyRaidBossSupportTargetCount/);\n});\n\ntest("SKY RAID Formation Rush has a reusable WebGL burst language and lens kick", () => {\n  const raidSource = readFileSync(new URL("../src/sky/SkyDancerSkyRaid.ts", import.meta.url), "utf8");\n  assert.match(raidSource, /function buildRushFx\(\): THREE\.Group/);\n  assert.match(raidSource, /sky-raid-rush-fx/);\n  assert.match(raidSource, /visual\.rushBurst = Math\.max\(visual\.rushBurst, 1\.35\)/);\n  assert.match(raidSource, /rushCamera \* 1\.8/);\n  assert.match(raidSource, /skyRaidRushFxIntensity/);\n});\n'''
    return source + append


def patch_docs(source: str) -> str:
    block = '''\n## Act flight identity pass\n\nThe five acts now change the aircraft response as well as the scenery and enemy package. Dawn City is the neutral reference, Red Canyon favors fast bank/turn response, Cloud Fleet gives stronger vertical authority, Storm Carrier is the fastest and most reactive act, and Prism Citadel deliberately feels heavier during the siege. Formation Rush also owns a reusable additive ring burst and a small camera lens kick. At 7:30 the Prism Titan gains one extra support aircraft (capped at eight regular targets) and a tighter five-aircraft combat-lane choreography so the final minute escalates without becoming unreadable on iPhone.\n'''
    return source + block


update("src/sky/SkyDancerSkyRaidRules.ts", patch_rules)
update("src/sky/SkyDancerSkyRaidFlight.ts", patch_flight)
update("src/sky/SkyDancerSkyRaid.ts", patch_raid)
update("tests/sky-sky-raid.test.ts", patch_tests)
update("docs/SKY_RAID.md", patch_docs)
