import type { SkyDancerArcadeEnemyKind } from "./SkyDancerArcadeData";
import { skyDancerArcadeV24FlightProfile } from "./SkyDancerArcadeV24FlightDynamics";

export interface SkyDancerArcadeV25FlightState {
  x: number;
  y: number;
  vx: number;
  vy: number;
  bank: number;
  pitch: number;
  energy: number;
}

export interface SkyDancerArcadeV25ControlProfile {
  maxBank: number;
  maxPitch: number;
  rollRate: number;
  pitchRate: number;
  turnAcceleration: number;
  climbAcceleration: number;
  bankGain: number;
  pitchGain: number;
  energyRecovery: number;
  turnEnergyCost: number;
  climbEnergyCost: number;
}

export interface SkyDancerArcadeV25VisualAttitude {
  headingOffset: number;
  bank: number;
  pitchOffset: number;
}

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));
const moveToward = (current: number, target: number, maxDelta: number) => {
  if (current < target) return Math.min(target, current + maxDelta);
  if (current > target) return Math.max(target, current - maxDelta);
  return target;
};

export function skyDancerArcadeV25ControlProfile(
  kind: SkyDancerArcadeEnemyKind | "boss",
): SkyDancerArcadeV25ControlProfile {
  switch (kind) {
    case "drone": return { maxBank: .94, maxPitch: .46, rollRate: 3.8, pitchRate: 2.9, turnAcceleration: 9.6, climbAcceleration: 7.8, bankGain: .72, pitchGain: .56, energyRecovery: .26, turnEnergyCost: .145, climbEnergyCost: .105 };
    case "interceptor": return { maxBank: .9, maxPitch: .44, rollRate: 3.45, pitchRate: 2.72, turnAcceleration: 9.1, climbAcceleration: 7.25, bankGain: .74, pitchGain: .58, energyRecovery: .27, turnEnergyCost: .135, climbEnergyCost: .1 };
    case "raider": return { maxBank: .88, maxPitch: .43, rollRate: 3.15, pitchRate: 2.58, turnAcceleration: 8.7, climbAcceleration: 7.0, bankGain: .76, pitchGain: .59, energyRecovery: .25, turnEnergyCost: .14, climbEnergyCost: .103 };
    case "ace": return { maxBank: .98, maxPitch: .47, rollRate: 3.65, pitchRate: 2.92, turnAcceleration: 9.45, climbAcceleration: 7.55, bankGain: .76, pitchGain: .6, energyRecovery: .31, turnEnergyCost: .125, climbEnergyCost: .094 };
    case "striker": return { maxBank: .82, maxPitch: .4, rollRate: 2.75, pitchRate: 2.3, turnAcceleration: 7.8, climbAcceleration: 6.25, bankGain: .77, pitchGain: .6, energyRecovery: .23, turnEnergyCost: .145, climbEnergyCost: .108 };
    case "fighter": return { maxBank: .84, maxPitch: .41, rollRate: 2.9, pitchRate: 2.42, turnAcceleration: 8.15, climbAcceleration: 6.5, bankGain: .78, pitchGain: .61, energyRecovery: .21, turnEnergyCost: .15, climbEnergyCost: .11 };
    case "missile-boat": return { maxBank: .62, maxPitch: .31, rollRate: 1.7, pitchRate: 1.55, turnAcceleration: 5.25, climbAcceleration: 4.25, bankGain: .82, pitchGain: .65, energyRecovery: .18, turnEnergyCost: .155, climbEnergyCost: .12 };
    case "bomber": return { maxBank: .52, maxPitch: .26, rollRate: 1.28, pitchRate: 1.22, turnAcceleration: 4.15, climbAcceleration: 3.55, bankGain: .86, pitchGain: .7, energyRecovery: .16, turnEnergyCost: .165, climbEnergyCost: .13 };
    case "gunship": return { maxBank: .46, maxPitch: .23, rollRate: 1.05, pitchRate: 1.0, turnAcceleration: 3.55, climbAcceleration: 3.05, bankGain: .9, pitchGain: .74, energyRecovery: .14, turnEnergyCost: .175, climbEnergyCost: .138 };
    default: return { maxBank: .48, maxPitch: .24, rollRate: 1.12, pitchRate: 1.05, turnAcceleration: 3.7, climbAcceleration: 3.2, bankGain: .88, pitchGain: .72, energyRecovery: .15, turnEnergyCost: .17, climbEnergyCost: .135 };
  }
}

/**
 * V25 coordinated-turn controller.
 *
 * V24 removed teleport-like strafing. V25 goes one layer deeper: lateral acceleration is now
 * generated by bank angle, so the aircraft rolls first and its flight path bends afterwards.
 * Pitch works the same way vertically. Sustained high-G turns and climbs spend a small energy
 * reserve while unloading/descent recovers it, giving heavy and light aircraft visibly different
 * turn radii without turning Arcade Run into a simulator.
 */
export function skyDancerArcadeV25Step(
  state: SkyDancerArcadeV25FlightState,
  targetX: number,
  targetY: number,
  kind: SkyDancerArcadeEnemyKind | "boss",
  delta: number,
  urgency = 1,
  xLimit = 2.62,
  yLimit = 2.05,
): SkyDancerArcadeV25FlightState {
  const base = skyDancerArcadeV24FlightProfile(kind);
  const control = skyDancerArcadeV25ControlProfile(kind);
  const dt = clamp(delta, 0, .05);
  const response = clamp(urgency, .55, 1.35);
  const energy = clamp(state.energy, .58, 1.06);
  const energyAuthority = clamp(.7 + energy * .3, .86, 1.02);
  const errorX = clamp(targetX, -xLimit, xLimit) - state.x;
  const errorY = clamp(targetY, -yLimit, yLimit) - state.y;

  const maxVX = base.maxLateralSpeed * energyAuthority;
  const maxVY = base.maxVerticalSpeed * energyAuthority;
  const desiredVX = clamp(errorX * base.positionGain * response, -maxVX, maxVX);
  const desiredVY = clamp(errorY * base.positionGain * response, -maxVY, maxVY);

  const desiredBank = clamp((desiredVX - state.vx) * control.bankGain, -control.maxBank, control.maxBank);
  const desiredPitch = clamp((desiredVY - state.vy) * control.pitchGain, -control.maxPitch, control.maxPitch);
  let bank = moveToward(state.bank, desiredBank, control.rollRate * response * dt);
  let pitch = moveToward(state.pitch, desiredPitch, control.pitchRate * response * dt);

  const bankNorm = control.maxBank > 0 ? clamp(bank / control.maxBank, -1, 1) : 0;
  const pitchNorm = control.maxPitch > 0 ? clamp(pitch / control.maxPitch, -1, 1) : 0;
  const turnCurve = Math.sin(bankNorm * Math.PI * .5);
  const pitchCurve = Math.sin(pitchNorm * Math.PI * .5);
  let vx = state.vx + turnCurve * control.turnAcceleration * energyAuthority * dt;
  let vy = state.vy + pitchCurve * control.climbAcceleration * energyAuthority * dt;

  vx = clamp(vx, -maxVX, maxVX);
  vy = clamp(vy, -maxVY, maxVY);
  if (Math.abs(errorX) < .07) vx *= Math.exp(-base.velocityDamping * 1.08 * dt);
  if (Math.abs(errorY) < .06) vy *= Math.exp(-base.velocityDamping * 1.05 * dt);

  let x = clamp(state.x + vx * dt, -xLimit, xLimit);
  let y = clamp(state.y + vy * dt, -yLimit, yLimit);
  if (Math.abs(x) >= xLimit - 1e-4 && Math.sign(vx) === Math.sign(x)) {
    vx *= .3;
    bank = moveToward(bank, 0, control.rollRate * dt * 1.4);
  }
  if (Math.abs(y) >= yLimit - 1e-4 && Math.sign(vy) === Math.sign(y)) {
    vy *= .3;
    pitch = moveToward(pitch, 0, control.pitchRate * dt * 1.4);
  }

  const turnLoad = Math.abs(bankNorm);
  const climbLoad = Math.max(0, pitchNorm);
  const descentRecovery = Math.max(0, -pitchNorm) * control.energyRecovery * .46;
  const load = turnLoad * control.turnEnergyCost + climbLoad * control.climbEnergyCost;
  // V25.1: an aircraft cannot fully recover energy while it is still pulling hard. Recovery belongs
  // to the unload/descent phase, leaving a readable speed consequence after a sustained turn.
  const aerodynamicLoad = Math.max(turnLoad, climbLoad * .85);
  const unloadedRecovery = control.energyRecovery
    * Math.max(0, 1.025 - energy)
    * Math.max(.08, 1 - aerodynamicLoad * .88);
  const recovery = unloadedRecovery + descentRecovery;
  const nextEnergy = clamp(energy + (recovery - load) * dt, .58, 1.06);

  x = clamp(x, -xLimit, xLimit);
  y = clamp(y, -yLimit, yLimit);
  return { x, y, vx, vy, bank, pitch, energy: nextEnergy };
}

/** Small closure-speed modulation: hard turns/climbs bleed speed, unloading restores it. */
export function skyDancerArcadeV25ClosureScale(
  kind: SkyDancerArcadeEnemyKind | "boss",
  energy: number,
  bank: number,
  pitch: number,
  maneuver: string,
): number {
  const control = skyDancerArcadeV25ControlProfile(kind);
  const turnLoad = control.maxBank > 0 ? Math.abs(bank) / control.maxBank : 0;
  const climbLoad = control.maxPitch > 0 ? Math.max(0, pitch) / control.maxPitch : 0;
  const maneuverBoost = maneuver === "overtake" ? .07 : maneuver === "approach" ? .018 : 0;
  return clamp(.955 + (clamp(energy, .58, 1.06) - .76) * .2 - turnLoad * .065 - climbLoad * .035 + maneuverBoost, .82, 1.08);
}

/**
 * Render attitude derived from acceleration, not just screen velocity. This makes the wing roll
 * visibly precede the change in trajectory and prevents the old sideways-skid impression.
 */
export function skyDancerArcadeV25VisualAttitude(
  lateralVelocity: number,
  verticalVelocity: number,
  lateralAcceleration: number,
  verticalAcceleration: number,
  maneuver: string,
): SkyDancerArcadeV25VisualAttitude {
  const hardTurn = maneuver === "cross-pass" || maneuver === "close-bank";
  const headingScale = hardTurn ? .11 : maneuver === "overtake" ? .095 : .082;
  const accelerationHeading = hardTurn ? .018 : .012;
  const maxBank = hardTurn ? .82 : .68;
  const headingOffset = clamp(lateralVelocity * headingScale + lateralAcceleration * accelerationHeading, -.38, .38);
  const bank = clamp(-lateralAcceleration * (hardTurn ? .075 : .065) - lateralVelocity * .025, -maxBank, maxBank);
  const pitchOffset = clamp(verticalVelocity * .05 + verticalAcceleration * .013 + Math.abs(bank) * .028, -.26, .28);
  return { headingOffset, bank, pitchOffset };
}
