import type { RallyTrackDefinition, TrackControlPoint } from "./TrackDefinition";

export const TRACK_03_CONTROL_POINTS: readonly TrackControlPoint[] = [
  { x: 0, z: 20, y: 0.8, width: 19 },
  { x: 90, z: 20, y: 1, width: 19 },
  { x: 130, z: 32, y: 1.4, width: 20 },
  { x: 145, z: 65, y: 2.2, width: 18 },
  { x: 145, z: 110, y: 3, width: 19 },
  { x: 120, z: 145, y: 4.5, width: 20 },
  { x: 70, z: 170, y: 5.2, width: 19 },
  { x: 0, z: 178, y: 4.6, width: 20 },
  { x: -70, z: 170, y: 3.2, width: 19 },
  { x: -120, z: 145, y: 2, width: 18 },
  { x: -145, z: 110, y: 1.2, width: 19 },
  { x: -145, z: 65, y: 0.9, width: 20 },
  { x: -130, z: 32, y: 0.8, width: 19 },
  { x: -90, z: 20, y: 0.8, width: 18 },
  // Pull the return lane farther away from the opening straight. The old
  // closure came within one road width of the start and made an off-road
  // hover query legitimately ambiguous at high speed.
  { x: -45, z: -15, y: 1.1, width: 19 },
  { x: 0, z: -28, y: 1.8, width: 20 },
  { x: 45, z: -15, y: 2.5, width: 19 },
  { x: 90, z: 5, y: 1.9, width: 18 },
];

export const TRACK_03: RallyTrackDefinition = {
  id: "track-03",
  name: "Voxel Badlands",
  controlPoints: TRACK_03_CONTROL_POINTS,
  roadWidth: 19,
  checkpoints: [0.2, 0.47, 0.74],
  startDistance: 0,
  surfaceZones: [
    { id: "badlands-dirt-1", start: 0.08, end: 0.3, surface: "dirt" },
    { id: "badlands-grass-1", start: 0.3, end: 0.42, surface: "grass" },
    { id: "badlands-mud-2", start: 0.52, end: 0.68, surface: "mud" },
    { id: "badlands-grass-2", start: 0.82, end: 0.96, surface: "grass" },
  ],
  gameplayBeats: [
    { id: "badlands-safe-opening", progress: 0.04, kind: "safe-route", label: "SAFE ROUTE" },
    { id: "badlands-fast-opening", progress: 0.13, kind: "fast-route", label: "FAST ROUTE" },
    { id: "badlands-destruction-opening", progress: 0.17, kind: "destruction-route", label: "DESTRUCTION ROUTE" },
    { id: "badlands-jump-line", progress: 0.29, kind: "jump", label: "BIG JUMP" },
    { id: "badlands-off-road-basin", progress: 0.4, kind: "off-road", label: "OFF-ROAD BASIN" },
    { id: "badlands-safe-ruins", progress: 0.51, kind: "safe-route", label: "SAFE RUINS" },
    { id: "badlands-destruction-ruins", progress: 0.61, kind: "destruction-route", label: "SMASH RUINS" },
    { id: "badlands-fast-return", progress: 0.8, kind: "fast-route", label: "FAST RETURN" },
    { id: "badlands-finish-sprint", progress: 0.94, kind: "finish-sprint", label: "BADLANDS SPRINT" },
  ],
  environmentVariant: "dry",
  shortcutZones: [
    { id: "badlands-shortcut-west", entryX: -43, entryZ: 72, exitX: -28, exitZ: 99, obstacleId: "badlands-wall-01" },
    { id: "badlands-shortcut-east", entryX: 42, entryZ: 47, exitX: 24, exitZ: 81, obstacleId: "badlands-wall-02" },
    { id: "badlands-shortcut-ruins", entryX: 27, entryZ: 142, exitX: 1, exitZ: 119, obstacleId: "badlands-wall-03" },
  ],
  obstacles: [
    { id: "badlands-cracked-rock-01", progress: 0.08, lateral: 0.55, radius: 2.8, kind: "rock", destructible: true, pattern: "pickup-behind-wall" },
    { id: "badlands-cracked-rock-02", progress: 0.24, lateral: -0.58, radius: 2.5, kind: "rock", destructible: true, pattern: "slalom" },
    { id: "badlands-cracked-rock-03", progress: 0.5, lateral: 0.48, radius: 2.4, kind: "rock", destructible: true, pattern: "offset-wall" },
    { id: "badlands-ruin-01", progress: 0.58, lateral: -0.62, radius: 2.2, kind: "barrier", destructible: true, pattern: "slalom" },
    { id: "badlands-ruin-02", progress: 0.7, lateral: 0.62, radius: 2.4, kind: "barrier", destructible: true, pattern: "offset-wall" },
    { id: "badlands-wall-01", x: -38, z: 84, radius: 2.5, kind: "wall", destructible: true, pattern: "smash-line" },
    { id: "badlands-wall-02", x: 34, z: 65, radius: 2.3, kind: "wall", destructible: true, pattern: "smash-line" },
    { id: "badlands-wall-03", x: 15, z: 132, radius: 2.6, kind: "wall", destructible: true, pattern: "pickup-behind-wall" },
    { id: "badlands-boost-gate", progress: 0.34, lateral: 0.64, radius: 2.4, kind: "wall", destructible: true, pattern: "wall-gate" },
    { id: "badlands-smash-return", progress: 0.63, lateral: -0.62, radius: 2.4, kind: "wall", destructible: true, pattern: "smash-line" },
    { id: "badlands-slalom-a", progress: 0.22, lateral: 0.7, radius: 2.2, kind: "wall", destructible: true, pattern: "slalom" },
    { id: "badlands-slalom-b", progress: 0.27, lateral: -0.7, radius: 2.2, kind: "wall", destructible: true, pattern: "slalom" },
    { id: "badlands-wall-gate", progress: 0.43, lateral: 0, radius: 2.6, kind: "wall", destructible: true, pattern: "wall-gate" },
    { id: "badlands-double-gap", progress: 0.37, lateral: 0, radius: 2.1, kind: "wall", destructible: true, pattern: "double-gap" },
    { id: "badlands-enemy-wall", progress: 0.76, lateral: 0, radius: 2.1, kind: "wall", destructible: true, pattern: "enemy-wall" },
    { id: "badlands-final-wall", progress: 0.9, lateral: 0.58, radius: 2.4, kind: "wall", destructible: true, pattern: "smash-line" },
  ],
  safetyBlockZones: [
    { id: "badlands-opening-safety", startProgress: 0.05, endProgress: 0.11, side: "right", offset: 1.8, spacing: 3, blockType: "voxel-safety" },
    { id: "badlands-fast-curve-safety", startProgress: 0.45, endProgress: 0.5, side: "left", offset: 1.8, spacing: 3, blockType: "voxel-safety" },
    { id: "badlands-outer-blocks", startProgress: 0.51, endProgress: 0.55, side: "left", offset: 1.8, spacing: 3, blockType: "voxel-safety" },
    { id: "badlands-outer-right-blocks", startProgress: 0.55, endProgress: 0.59, side: "right", offset: 1.8, spacing: 3, blockType: "voxel-safety" },
    { id: "badlands-ruin-blocks", startProgress: 0.59, endProgress: 0.65, side: "left", offset: 1.8, spacing: 3, blockType: "voxel-safety" },
    { id: "badlands-finish-blocks", startProgress: 0.88, endProgress: 0.94, side: "left", offset: 1.8, spacing: 3, blockType: "voxel-safety" },
  ],
  pickups: [
    { id: "badlands-boost-01", progress: 0.035, lateral: -0.68 },
    { id: "badlands-boost-02", progress: 0.08, lateral: 0.7 },
    { id: "badlands-boost-03", progress: 0.14, lateral: -0.78 },
    { id: "badlands-boost-04", progress: 0.19, lateral: 0.72 },
    { id: "badlands-boost-05", progress: 0.27, lateral: -0.6 },
    { id: "badlands-boost-06", progress: 0.36, lateral: 0.75 },
    { id: "badlands-boost-07", progress: 0.48, lateral: -0.7 },
    { id: "badlands-boost-08", progress: 0.56, lateral: 0.76 },
    { id: "badlands-boost-09", progress: 0.63, lateral: -0.8 },
    { id: "badlands-boost-10", progress: 0.71, lateral: 0.72 },
    { id: "badlands-boost-11", progress: 0.82, lateral: -0.72 },
    { id: "badlands-boost-12", progress: 0.9, lateral: 0.7 },
    { id: "badlands-boost-13", progress: 0.96, lateral: -0.62 },
  ],
  routeGraph: {
    startNodeId: "start",
    finishNodeId: "finish",
    nodes: [
      { id: "start", progress: 0 },
      { id: "cp-1", progress: 0.2 },
      { id: "cp-2", progress: 0.47 },
      { id: "cp-3", progress: 0.74 },
      { id: "finish", progress: 1 },
    ],
    edges: [
      {
        id: "badlands-main-1", from: "start", to: "cp-1", kind: "normal", distance: 120, difficulty: 1,
        speedRequirement: 0, requiresDestruction: false, risk: 0.1, startProgress: 0, endProgress: 0.2,
        entryX: 0, entryZ: 20, exitX: 47, exitZ: 34, corridorRadius: 18,
      },
      {
        id: "badlands-destroy-1", from: "start", to: "cp-1", kind: "destructible", distance: 92, difficulty: 3,
        speedRequirement: 10, requiresDestruction: true, risk: 0.55, startProgress: 0, endProgress: 0.2,
        entryX: 42, entryZ: 28, exitX: 29, exitZ: 68, corridorRadius: 12,
      },
      {
        id: "badlands-main-2", from: "cp-1", to: "cp-2", kind: "normal", distance: 165, difficulty: 2,
        speedRequirement: 0, requiresDestruction: false, risk: 0.2, startProgress: 0.2, endProgress: 0.47,
        entryX: 31, entryZ: 74, exitX: -13, exitZ: 111, corridorRadius: 20,
      },
      {
        id: "badlands-jump-2", from: "cp-1", to: "cp-2", kind: "jump", distance: 137, difficulty: 4,
        speedRequirement: 14, requiresDestruction: false, risk: 0.7, startProgress: 0.2, endProgress: 0.47,
        entryX: 5, entryZ: 69, exitX: -38, exitZ: 103, corridorRadius: 14,
      },
      {
        id: "badlands-main-3", from: "cp-2", to: "cp-3", kind: "normal", distance: 180, difficulty: 2,
        speedRequirement: 0, requiresDestruction: false, risk: 0.25, startProgress: 0.47, endProgress: 0.74,
        entryX: -48, entryZ: 123, exitX: 51, exitZ: 108, corridorRadius: 22,
      },
      {
        id: "badlands-ruin-3", from: "cp-2", to: "cp-3", kind: "destructible", distance: 143, difficulty: 4,
        speedRequirement: 11, requiresDestruction: true, risk: 0.6, startProgress: 0.47, endProgress: 0.74,
        entryX: -35, entryZ: 148, exitX: 18, exitZ: 111, corridorRadius: 15,
      },
      {
        id: "badlands-finish", from: "cp-3", to: "finish", kind: "off-road", distance: 150, difficulty: 2,
        speedRequirement: 0, requiresDestruction: false, risk: 0.3, startProgress: 0.74, endProgress: 1,
        entryX: 35, entryZ: 92, exitX: 0, exitZ: 20, corridorRadius: 24,
      },
    ],
  },
  scenery: { count: 88, radiusX: 46, radiusZ: 88 },
  medalTimes: { gold: 42, silver: 53, bronze: 68 },
};
