import type { RallyTrackDefinition, TrackControlPoint } from "./TrackDefinition";

export const TRACK_02_CONTROL_POINTS: readonly TrackControlPoint[] = [
  { x: 0, z: 12, y: 1, width: 16 },
  { x: 82, z: 15, y: 2.2, width: 16 },
  { x: 104, z: 29, y: 3.8, width: 16.5 },
  { x: 98, z: 51, y: 5.2, width: 15.5 },
  { x: 62, z: 66, y: 5.8, width: 15.5 },
  { x: 18, z: 64, y: 6.1, width: 15.2 },
  { x: -25, z: 50, y: 6.5, width: 15 },
  { x: -48, z: 30, y: 6.9, width: 15.2 },
  { x: -42, z: 8, y: 7.3, width: 15.5 },
  { x: -12, z: -4, y: 7.8, width: 16 },
  { x: 24, z: 6, y: 7.5, width: 16 },
  { x: 58, z: 24, y: 6.9, width: 15.5 },
  { x: 72, z: 52, y: 5.8, width: 15 },
  { x: 68, z: 86, y: 4.2, width: 15.5 },
  { x: 34, z: 112, y: 3.4, width: 16 },
  { x: -10, z: 120, y: 2.6, width: 16.2 },
  { x: -48, z: 108, y: 1.8, width: 15.8 },
  { x: -70, z: 78, y: 1.2, width: 15.5 },
  { x: -76, z: 45, y: 0.8, width: 16 },
  { x: -56, z: 18, y: 0.7, width: 15.5 },
  { x: -20, z: 4, y: 0.8, width: 16 },
];

export const TRACK_02: RallyTrackDefinition = {
  id: "track-02",
  name: "Mountain Pass",
  controlPoints: TRACK_02_CONTROL_POINTS,
  roadWidth: 16,
  checkpoints: [0.23, 0.49, 0.74],
  startDistance: 0,
  surfaceZones: [
    { id: "mountain-dirt-up", start: 0.24, end: 0.42, surface: "dirt" },
    { id: "mountain-rock-down", start: 0.67, end: 0.81, surface: "rock" },
  ],
  gameplayBeats: [
    { id: "mountain-opening-climb", progress: 0.04, kind: "straight", label: "OPENING CLIMB" },
    { id: "mountain-risk-shortcut", progress: 0.14, kind: "destructible-shortcut", label: "RISK SHORTCUT" },
    { id: "mountain-hairpin-one", progress: 0.28, kind: "hairpin", label: "HAIRPIN 1" },
    { id: "mountain-hairpin-two", progress: 0.44, kind: "hairpin", label: "HAIRPIN 2" },
    { id: "mountain-crest-jump", progress: 0.58, kind: "jump", label: "CREST JUMP" },
    { id: "mountain-rock-tunnel", progress: 0.7, kind: "rock-tunnel", label: "ROCK TUNNEL" },
    { id: "mountain-long-descent", progress: 0.82, kind: "descent", label: "LONG DESCENT" },
    { id: "mountain-finish-run", progress: 0.94, kind: "finish-sprint", label: "FINISH RUN" },
  ],
  environmentVariant: "sunset",
  shortcutZones: [
    { id: "mountain-shortcut", entryX: 25, entryZ: 50, exitX: 8, exitZ: 67, obstacleId: "mountain-wall-01" },
  ],
  obstacles: [
    { id: "mountain-cracked-rock-01", progress: 0.12, lateral: -0.52, radius: 2.1, kind: "rock", destructible: true, pattern: "offset-wall" },
    { id: "mountain-cracked-rock-02", progress: 0.32, lateral: 0.58, radius: 1.8, kind: "rock", destructible: true, pattern: "pickup-behind-wall" },
    { id: "mountain-cracked-rock-03", progress: 0.64, lateral: -0.58, radius: 1.9, kind: "rock", destructible: true, pattern: "slalom" },
    { id: "mountain-voxel-barrier-01", progress: 0.55, lateral: -0.5, radius: 1.4, kind: "barrier", destructible: true, pattern: "slalom" },
    { id: "mountain-wall-01", x: 18, z: 57, radius: 2.1, kind: "wall", destructible: true, pattern: "smash-line" },
    { id: "mountain-voxel-gate", progress: 0.36, lateral: 0.66, radius: 2.0, kind: "wall", destructible: true, pattern: "wall-gate" },
    { id: "mountain-descent-gate", progress: 0.68, lateral: -0.62, radius: 2.0, kind: "wall", destructible: true, pattern: "wall-gate" },
    { id: "mountain-enemy-wall", progress: 0.79, lateral: 0.12, radius: 1.8, kind: "wall", destructible: true, pattern: "enemy-wall" },
    { id: "mountain-finish-wall", progress: 0.88, lateral: -0.7, radius: 2.0, kind: "wall", destructible: true, pattern: "offset-wall" },
    { id: "mountain-descent-pillar", progress: 0.76, lateral: 0.62, radius: 1.8, kind: "wall", destructible: true, pattern: "slalom" },
    { id: "mountain-final-gate", progress: 0.96, lateral: 0.05, radius: 1.9, kind: "wall", destructible: true, pattern: "smash-line" },
  ],
  safetyBlockZones: [
    { id: "mountain-hairpin-one-safety", startProgress: 0.27, endProgress: 0.33, side: "left", offset: 1.5, spacing: 2.7, blockType: "voxel-safety" },
    { id: "mountain-rock-tunnel-safety", startProgress: 0.67, endProgress: 0.73, side: "left", offset: 1.5, spacing: 2.7, blockType: "voxel-safety" },
    { id: "mountain-descent-safety", startProgress: 0.77, endProgress: 0.83, side: "left", offset: 1.5, spacing: 2.7, blockType: "voxel-safety" },
    { id: "mountain-final-safety", startProgress: 0.93, endProgress: 0.99, side: "left", offset: 1.5, spacing: 2.7, blockType: "voxel-safety" },
  ],
  pickups: [
    { id: "mountain-boost-01", progress: 0.03, lateral: 0.58 },
    { id: "mountain-boost-02", progress: 0.11, lateral: -0.62 },
    { id: "mountain-boost-03", progress: 0.2, lateral: 0.68 },
    { id: "mountain-boost-04", progress: 0.34, lateral: -0.58 },
    { id: "mountain-boost-05", progress: 0.42, lateral: 0.58 },
    { id: "mountain-boost-06", progress: 0.53, lateral: -0.68 },
    { id: "mountain-boost-07", progress: 0.61, lateral: 0.62 },
    { id: "mountain-boost-08", progress: 0.72, lateral: -0.6 },
    { id: "mountain-boost-09", progress: 0.82, lateral: 0.58 },
    { id: "mountain-boost-10", progress: 0.93, lateral: -0.52 },
  ],
  scenery: { count: 64, radiusX: 34, radiusZ: 72 },
  medalTimes: { gold: 38, silver: 47, bronze: 60 },
};
