from pathlib import Path

world = Path('src/sky/arcade/SkyDancerArcadeReferenceWorld.ts')
s = world.read_text()

old = '''    this.backdrop=this.buildBackdrop(stage);\n    this.backdrop.userData.arcadeBackdropCourseFollowV1035=stage.biome!=="orbit"&&stage.biome!=="citadel";\n    this.root.add(hemi,key,rim,createArcadeSky(stage),this.backdrop);'''
new = '''    this.backdrop=this.buildBackdrop(stage);\n    // V10.3.6: the distant horizon is a camera/world reference, not another streamed course chunk.\n    // Keeping it transform-stable prevents the whole skyline from sliding independently of the route.\n    this.backdrop.userData.arcadeBackdropStableHorizonV1036=true;\n    this.root.add(hemi,key,rim,createArcadeSky(stage),this.backdrop);'''
assert old in s
s = s.replace(old, new, 1)

old = '''      const skylineStage=this.stage.biome==="city"||this.stage.biome==="night";\n      // V10.3.5: city architecture is a scenery wall, not the flight deck itself.\n      // Let the continuous river/banks carry the exact turn and keep rigid building chunks from over-banking.\n      chunk.group.rotation.y=course.yaw*(skylineStage?.82:1.08);\n      chunk.group.rotation.x=course.pitch*(skylineStage?.7:.94);\n      chunk.group.rotation.z=course.bank*(skylineStage?.23:.38);\n    }\n    if(this.backdrop)this.updateBackdrop(distance);\n    if(this.cityRiver)this.updateCityRiver(distance,playerX,playerY);'''
new = '''      const skylineStage=this.stage.biome==="city"||this.stage.biome==="night";\n      const bankScale=skylineStage?.22:this.stage.biome==="ice"?.26:this.stage.biome==="volcano"?.28:.38;\n      // V10.3.6: every course-bound chunk now uses the exact same yaw/pitch frame as the spline ribbons.\n      // The former .82/.70 skyline factors made buildings rotate on a different frame than river/ground,\n      // which read as the background drifting or detaching during turns.\n      chunk.group.rotation.y=course.yaw;\n      chunk.group.rotation.x=course.pitch;\n      chunk.group.rotation.z=course.bank*bankScale;\n      chunk.group.userData.arcadeUnifiedCourseFrameV1036=true;\n    }\n    if(this.cityRiver)this.updateCityRiver(distance,playerX,playerY);'''
assert old in s
s = s.replace(old, new, 1)

old = '''      cue.group.rotation.y=course.yaw*1.1;\n      cue.group.rotation.x=cue.kind==="ice" ? course.pitch*1.05+cueSlope*.9 : course.pitch*1.02;\n      cue.group.rotation.z=cue.kind==="orbit"\n        ? cue.phase+(distance+cue.depth)*.0068+course.bank*.24\n        : course.bank*(cue.kind==="ice"?.26:.3);'''
new = '''      const cueBankScale=cue.kind==="ice"?.26:cue.kind==="volcano"?.28:.38;\n      // V10.3.6: route markers share the same yaw/pitch frame as the streamed course.\n      // Only the authored ice slope correction and orbital spin remain as intentional local rotations.\n      cue.group.rotation.y=course.yaw;\n      cue.group.rotation.x=cue.kind==="ice" ? course.pitch+cueSlope*.9 : course.pitch;\n      cue.group.rotation.z=cue.kind==="orbit"\n        ? cue.phase+(distance+cue.depth)*.0068+course.bank*cueBankScale\n        : course.bank*cueBankScale;'''
assert old in s
s = s.replace(old, new, 1)

old = '''  private updateBackdrop(distance:number):void {\n    if(!this.stage||!this.backdrop)return;\n    const followsCourse=this.stage.biome!=="orbit"&&this.stage.biome!=="citadel";\n    if(!followsCourse){\n      this.backdrop.position.set(0,0,0);\n      this.backdrop.rotation.set(0,0,0);\n      return;\n    }\n    // V10.3.5: the old far field was world-fixed while the streamed corridor used course-relative coordinates.\n    // On video that made the skyline visibly slide sideways against the river whenever the route turned.\n    // Anchor the far field to a distant sample of the same spline. It deliberately follows less than the\n    // foreground so the shot keeps depth parallax without looking like two unrelated worlds.\n    const cityLike=this.stage.biome==="city"||this.stage.biome==="night";\n    const depth=cityLike?430:520;\n    const far=arcadeCourseRelativePose(this.stage,distance,depth);\n    this.backdrop.position.x=far.x*(cityLike?.72:.58);\n    this.backdrop.position.y=far.y*(cityLike?.46:.38);\n    this.backdrop.position.z=0;\n    this.backdrop.rotation.set(0,0,0);\n    this.backdrop.userData.arcadeBackdropDepthV1035=depth;\n    this.backdrop.userData.arcadeBackdropXFollowV1035=cityLike?.72:.58;\n    this.backdrop.userData.arcadeBackdropYFollowV1035=cityLike?.46:.38;\n  }\n\n'''
assert old in s
s = s.replace(old, '', 1)
world.write_text(s)

test = Path('tests/sky-arcade-reference.test.ts')
s = test.read_text()
old = '''test("V10.3.5 far-field skyline follows the same course without steering swim or city over-bank", () => {\n  const city=SKY_DANCER_ARCADE_STAGES.find(stage=>stage.biome==="city");\n  assert.ok(city);\n  const scene=new THREE.Scene();\n  const world=new SkyDancerArcadeReferenceWorld(scene);\n  world.setStage(city);\n  const backdrop=scene.getObjectByName("arcade-product-backdrop") as THREE.Group;\n  assert.ok(backdrop instanceof THREE.Group);\n  assert.equal(backdrop.userData.arcadeBackdropCourseFollowV1035,true);\n  assert.equal(backdrop.userData.arcadeBackdropDepthV1035,430);\n  const length=city.durationSeconds*city.courseSpeed;\n  const xs:number[]=[],ys:number[]=[];\n  let maxChunkBank=0;\n  for(const progress of [.06,.12,.18,.25,.32,.4]){\n    world.update(length*progress,0,0);\n    xs.push(backdrop.position.x);ys.push(backdrop.position.y);\n    for(let i=0;i<8;i++){\n      const chunk=scene.getObjectByName(`arcade-course-chunk-${i}`);\n      assert.ok(chunk);maxChunkBank=Math.max(maxChunkBank,Math.abs(chunk.rotation.z));\n    }\n  }\n  const range=(values:number[])=>Math.max(...values)-Math.min(...values);\n  assert.ok(range(xs)>2||range(ys)>1.5,`far field must follow the authored route: x=${range(xs)} y=${range(ys)}`);\n  assert.ok(maxChunkBank<.3,`dense city chunks should not over-bank: ${maxChunkBank}`);\n  world.update(length*.25,1,.8);const steeredX=backdrop.position.x,steeredY=backdrop.position.y;\n  world.update(length*.25,-1,-.8);\n  assert.ok(Math.abs(backdrop.position.x-steeredX)<1e-9&&Math.abs(backdrop.position.y-steeredY)<1e-9,"far skyline must not swim with steering input");\n  world.dispose();\n});'''
new = '''test("V10.3.6 keeps the horizon stable while every course-bound layer shares one spline frame", () => {\n  const city=SKY_DANCER_ARCADE_STAGES.find(stage=>stage.biome==="city");\n  const volcano=SKY_DANCER_ARCADE_STAGES.find(stage=>stage.biome==="volcano");\n  assert.ok(city && volcano);\n  const scene=new THREE.Scene();\n  const world=new SkyDancerArcadeReferenceWorld(scene);\n  world.setStage(city);\n  const backdrop=scene.getObjectByName("arcade-product-backdrop") as THREE.Group;\n  assert.ok(backdrop instanceof THREE.Group);\n  assert.equal(backdrop.userData.arcadeBackdropStableHorizonV1036,true);\n  const length=city.durationSeconds*city.courseSpeed;\n  for(const progress of [.06,.12,.18,.25,.32,.4]){\n    const distance=length*progress;\n    world.update(distance,.8,-.6);\n    assert.ok(backdrop.position.length()<1e-12,"far horizon must not translate independently of the course");\n    assert.ok(Math.abs(backdrop.rotation.x)+Math.abs(backdrop.rotation.y)+Math.abs(backdrop.rotation.z)<1e-12,\n      "far horizon must stay in the world/camera frame instead of receiving a second course rotation");\n    for(let i=0;i<8;i++){\n      const chunk=scene.getObjectByName(`arcade-course-chunk-${i}`) as THREE.Group;\n      assert.ok(chunk);\n      assert.equal(chunk.userData.arcadeUnifiedCourseFrameV1036,true);\n      const depth=-chunk.position.z;\n      const authored=arcadeCourseRelativePose(city,distance,depth);\n      assert.ok(Math.abs(chunk.rotation.y-authored.yaw)<1e-9,`chunk ${i} yaw must equal the shared course yaw`);\n      assert.ok(Math.abs(chunk.rotation.x-authored.pitch)<1e-9,`chunk ${i} pitch must equal the shared course pitch`);\n      assert.ok(Math.abs(chunk.rotation.z-authored.bank*.22)<1e-9,`chunk ${i} bank must match the city river/bank frame`);\n    }\n  }\n\n  world.setStage(volcano);\n  const volcanoDistance=volcano.durationSeconds*volcano.courseSpeed*.29;\n  world.update(volcanoDistance,-.7,.5);\n  const cues=scene.getObjectsByProperty("name","arcade-volcano-route-cue") as THREE.Group[];\n  assert.ok(cues.length>0);\n  for(const cue of cues){\n    const depth=Number(cue.userData.arcadeRouteDepth);\n    const authored=arcadeCourseRelativePose(volcano,volcanoDistance,depth);\n    assert.ok(Math.abs(cue.rotation.y-authored.yaw)<1e-9,"volcano marker yaw must use the same course frame");\n    assert.ok(Math.abs(cue.rotation.x-authored.pitch)<1e-9,"volcano marker pitch must use the same course frame");\n    assert.ok(Math.abs(cue.rotation.z-authored.bank*.28)<1e-9,"volcano marker bank must match the magma ribbon frame");\n  }\n  world.dispose();\n});'''
assert old in s
s = s.replace(old, new, 1)
test.write_text(s)
