from pathlib import Path

world = Path('src/sky/arcade/SkyDancerArcadeReferenceWorld.ts')
s = world.read_text()

s = s.replace(
'''      // V10.3: a floor fissure, not a luminous road filling the foreground.\n      outer:this.makeIceRibbonMesh(stage,10.5,"arcade-ice-course-fissure-outer",.18),\n      core:this.makeIceRibbonMesh(stage,1.6,"arcade-ice-course-fissure-core",.62),''',
'''      // V10.3.1: a thin irregular floor crack, never a luminous road through the centre of the frame.\n      outer:this.makeIceRibbonMesh(stage,5.2,"arcade-ice-course-fissure-outer",.11),\n      core:this.makeIceRibbonMesh(stage,.7,"arcade-ice-course-fissure-core",.46),''', 1)

old = '''      const half=width*.5;\n      const samples=attribute.count/2;\n      for(let i=0;i<samples;i++){\n        const depth=30+i*13.8;\n        const course=arcadeCourseRelativePose(stage,distance,depth);\n        const cx=course.x-playerX*.35;\n        const cy=course.y-playerY*.16-23.2+lift;\n        const cz=-depth;\n        const lateralX=Math.cos(course.yaw)*half;\n        const lateralZ=-Math.sin(course.yaw)*half;\n        const bankY=course.bank*half*.12;\n        const left=i*6,right=left+3;\n        array[left]=cx-lateralX;array[left+1]=cy-bankY;array[left+2]=cz-lateralZ;\n        array[right]=cx+lateralX;array[right+1]=cy+bankY;array[right+2]=cz+lateralZ;\n      }'''
new = '''      const half=width*.5;\n      const samples=attribute.count/2;\n      for(let i=0;i<samples;i++){\n        const depth=42+i*14.4;\n        const course=arcadeCourseRelativePose(stage,distance,depth);\n        const crackPhase=distance+depth;\n        const jitter=Math.sin(crackPhase*.091)*1.35+Math.sin(crackPhase*.037+1.7)*.85;\n        const widthScale=.38+.62*Math.abs(Math.sin(crackPhase*.061+i*.79));\n        const localHalf=half*widthScale;\n        const cx=course.x-playerX*.35+jitter;\n        const cy=course.y-playerY*.16-24.6+lift;\n        const cz=-depth;\n        const lateralX=Math.cos(course.yaw)*localHalf;\n        const lateralZ=-Math.sin(course.yaw)*localHalf;\n        const bankY=course.bank*localHalf*.08;\n        const left=i*6,right=left+3;\n        array[left]=cx-lateralX;array[left+1]=cy-bankY;array[left+2]=cz-lateralZ;\n        array[right]=cx+lateralX;array[right+1]=cy+bankY;array[right+2]=cz+lateralZ;\n      }'''
assert old in s, 'ice ribbon update block changed'
s = s.replace(old, new, 1)
s = s.replace('''    update(this.iceRibbon.outer,10.5,0);\n    update(this.iceRibbon.core,1.6,.07);''', '''    update(this.iceRibbon.outer,5.2,0);\n    update(this.iceRibbon.core,.7,.05);''', 1)

s = s.replace('''      color:stage.palette.accent,transparent:true,opacity:kind==="volcano"?.88:kind==="ice"?.5:.84,''', '''      color:stage.palette.accent,transparent:true,opacity:kind==="volcano"?.88:kind==="ice"?.38:.84,''', 1)
s = s.replace('''    const count=kind==="ice"?7:10;''', '''    const count=kind==="ice"?6:10;''', 1)
s = s.replace('''      const depth=kind==="ice"?42+i*58:26+i*43;''', '''      const depth=kind==="ice"?58+i*66:26+i*43;''', 1)
s = s.replace('''        const radius=18+(i%3===0?-1.5:i%3===1?1.2:2.1);\n        const arc=Math.PI*(i%3===0?.44:i%3===1?.54:.48);\n        const arch=mesh(cue,new THREE.TorusGeometry(radius,1.02,6,28,arc),i%2?secondary:primary,(i%2?1:-1)*3.8,-10.5,0);''', '''        const radius=15.5+(i%3===0?-1.2:i%3===1?.9:1.5);\n        const arc=Math.PI*(i%3===0?.36:i%3===1?.46:.41);\n        const arch=mesh(cue,new THREE.TorusGeometry(radius,.74,6,26,arc),i%2?secondary:primary,(i%2?1:-1)*3.4,-10.8,0);''', 1)
s = s.replace('''        const inner=mesh(cue,new THREE.TorusGeometry(radius*.9,.24,5,24,arc*.72),glow,(i%2?1:-1)*3.2,-10.1,.18);''', '''        const inner=mesh(cue,new THREE.TorusGeometry(radius*.9,.16,5,22,arc*.68),glow,(i%2?1:-1)*2.9,-10.4,.18);''', 1)

old_canyon = '''      case "canyon":{\n        for(const side of [-1,1])for(let j=0;j<4;j++){\n          const h=17+r(j+side*15)*32;\n          const rock=mesh(group,new THREE.CylinderGeometry(4+r(j+3)*5,8+r(j+5)*7,h,7,3),j%2?primary:secondary,side*(28+j%2*28),-25+h/2,-42+j*27);\n          rock.rotation.y=r(j+19)*2;\n        }\n        break;\n      }'''
new_canyon = '''      case "canyon":{\n        // V10.3.1 foreground safety: keep the knife-run walls dramatic without a near cliff swallowing half the phone.\n        group.userData.arcadeCanyonV1031Clearance=true;\n        for(const side of [-1,1])for(let j=0;j<4;j++){\n          const h=17+r(j+side*15)*30;\n          const rock=mesh(group,new THREE.CylinderGeometry(3.5+r(j+3)*4.2,6.5+r(j+5)*5.5,h,7,3),j%2?primary:secondary,side*(34+j%2*30),-25+h/2,-42+j*27);\n          rock.rotation.y=r(j+19)*2;\n        }\n        break;\n      }'''
assert old_canyon in s, 'canyon block changed'
s = s.replace(old_canyon, new_canyon, 1)
world.write_text(s)

materials = Path('src/sky/arcade/SkyDancerArcadeReferenceMaterials.ts')
s = materials.read_text()
old = '''export function referenceAtmosphere(stage: SkyDancerArcadeStageDefinition) {\n  const city = stage.biome === "city";\n  const night = ["night", "orbit", "citadel"].includes(stage.biome);\n  return {\n    zenith: new THREE.Color(city ? 0x0b6198 : stage.palette.sky),\n    horizon: new THREE.Color(city ? 0xffb866 : stage.palette.fog),\n    fog: new THREE.Color(city ? 0x879caf : stage.palette.fog),\n    cloudLight: new THREE.Color(city ? 0xffddb0 : night ? 0x7283b5 : stage.biome === "storm" ? 0x90a5b9 : 0xeaf6ff),\n    cloudShadow: new THREE.Color(city ? 0x405d78 : stage.biome === "storm" ? 0x253e5b : night ? 0x151e43 : 0x557b98),\n    key: city ? 0xffc77b : night ? 0x98b4ff : stage.biome === "volcano" ? 0xff774a : 0xffe7c4,\n    keyIntensity: city ? 3.35 : night ? 1.4 : 2.5,\n    ambient: city ? .7 : night ? .8 : 1.3,\n    night,\n  };\n}'''
new = '''export function referenceAtmosphere(stage: SkyDancerArcadeStageDefinition) {\n  const city = stage.biome === "city";\n  const cloud = stage.biome === "cloud";\n  const night = ["night", "orbit", "citadel"].includes(stage.biome);\n  const cloudHorizon = new THREE.Color(stage.palette.fog).lerp(new THREE.Color(stage.palette.secondary), .26);\n  const cloudFog = new THREE.Color(stage.palette.fog).lerp(new THREE.Color(stage.palette.secondary), .34);\n  return {\n    zenith: new THREE.Color(city ? 0x0b6198 : cloud ? 0x62b3dc : stage.palette.sky),\n    horizon: city ? new THREE.Color(0xffb866) : cloud ? cloudHorizon : new THREE.Color(stage.palette.fog),\n    fog: city ? new THREE.Color(0x879caf) : cloud ? cloudFog : new THREE.Color(stage.palette.fog),\n    cloudLight: new THREE.Color(city ? 0xffddb0 : cloud ? 0xd5ebf4 : night ? 0x7283b5 : stage.biome === "storm" ? 0x90a5b9 : 0xeaf6ff),\n    cloudShadow: new THREE.Color(city ? 0x405d78 : cloud ? 0x527a93 : stage.biome === "storm" ? 0x253e5b : night ? 0x151e43 : 0x557b98),\n    key: city ? 0xffc77b : night ? 0x98b4ff : stage.biome === "volcano" ? 0xff774a : 0xffe7c4,\n    keyIntensity: city ? 3.35 : cloud ? 2.15 : night ? 1.4 : 2.5,\n    ambient: city ? .7 : cloud ? 1.05 : night ? .8 : 1.3,\n    night,\n  };\n}'''
assert old in s, 'referenceAtmosphere block changed'
s = s.replace(old, new, 1)
materials.write_text(s)

tests = Path('tests/sky-arcade-reference.test.ts')
s = tests.read_text()
s = s.replace('''import { SkyDancerArcadeReferenceWorld } from "../src/sky/arcade/SkyDancerArcadeReferenceWorld";''', '''import { SkyDancerArcadeReferenceWorld } from "../src/sky/arcade/SkyDancerArcadeReferenceWorld";\nimport { referenceAtmosphere } from "../src/sky/arcade/SkyDancerArcadeReferenceMaterials";''', 1)
s = s.replace('''  assert.equal(cues.length,7);''', '''  assert.equal(cues.length,6);''', 1)
s = s.replace('''  assert.equal(arches.length,7);''', '''  assert.equal(arches.length,6);''', 1)
s = s.replace('''    assert.ok(parameters.arc < Math.PI*.58, "ice guide ribs must stay short/open rather than recreate a hoop tunnel");''', '''    assert.ok(parameters.arc < Math.PI*.5, "ice guide ribs must stay compact/open rather than recreate a hoop tunnel");''', 1)
s = s.replace('''    assert.ok(depth>=42,"nearest ice guide must stay out of the camera/airframe foreground");''', '''    assert.ok(depth>=58,"nearest ice guide must stay well outside the camera/airframe foreground");''', 1)
s = s.replace('''  assert.ok(Number(fissure.userData.arcadeIceRibbonWidth)<=11,\n    "glacial fissure must stay narrow enough to read as a floor crack, not a luminous road");''', '''  assert.ok(Number(fissure.userData.arcadeIceRibbonWidth)<=5.5,\n    "glacial fissure must stay narrow enough to read as a floor crack, not a luminous road");''', 1)
s = s.replace('''  assert.ok(fissureMaterial.opacity<=.2 && coreMaterial.opacity<=.65,\n    "ice fissure glow must not wash out the foreground");''', '''  assert.ok(fissureMaterial.opacity<=.12 && coreMaterial.opacity<=.5,\n    "ice fissure glow must not wash out the foreground");''', 1)
s = s.replace('''  assert.ok(firstCenterZ<=-26,\n    "continuous fissure must begin far enough ahead to avoid clipping into the camera/airframe");''', '''  assert.ok(firstCenterZ<=-38,\n    "continuous fissure must begin far enough ahead to avoid clipping into the camera/airframe");\n  const fissureWidths:number[]=[];\n  for(let i=0;i<fissurePosition.count;i+=2){\n    const dx=fissurePosition.getX(i)-fissurePosition.getX(i+1);\n    const dy=fissurePosition.getY(i)-fissurePosition.getY(i+1);\n    const dz=fissurePosition.getZ(i)-fissurePosition.getZ(i+1);\n    fissureWidths.push(Math.hypot(dx,dy,dz));\n  }\n  assert.ok(Math.max(...fissureWidths)-Math.min(...fissureWidths)>1.5,\n    "ice fissure width must vary enough to read as a natural crack instead of a constant-width road");''', 1)

cloud_anchor = '''  assert.equal(new Set(chunks.map((chunk)=>chunk.userData.arcadeCloudV92LeadSide)).size,2,\n    "hero warships must alternate sides to create fleet weave rather than a symmetric corridor");'''
cloud_repl = cloud_anchor + '''\n  const atmosphere=referenceAtmosphere(fleet);\n  assert.notEqual(atmosphere.fog.getHex(),fleet.palette.fog,\n    "Cloud Fleet needs a dedicated midtone fog grade so white ships remain readable against the cloud sea");\n  assert.ok(atmosphere.keyIntensity<2.3 && atmosphere.ambient<1.15,\n    "Cloud Fleet lighting must stay restrained enough to avoid white-out on mobile");'''
assert cloud_anchor in s, 'cloud test anchor changed'
s = s.replace(cloud_anchor, cloud_repl, 1)

insert = '''\n\ntest("V10.3.1 red canyon keeps dramatic walls outside the phone foreground safety lane", () => {\n  const scene=new THREE.Scene();\n  const world=new SkyDancerArcadeReferenceWorld(scene);\n  const canyon=SKY_DANCER_ARCADE_STAGES.find((stage)=>stage.id==="red-canyon")!;\n  world.setStage(canyon);\n  world.update(canyon.courseSpeed*6,0,0);\n  const environment=scene.getObjectByName("arcade-course-environment")!;\n  const chunks=environment.children.filter((object)=>object.name.startsWith("arcade-course-chunk-"));\n  assert.equal(chunks.length,8);\n  assert.ok(chunks.every((chunk)=>chunk.userData.arcadeCanyonV1031Clearance===true),\n    "every canyon chunk must preserve the V10.3.1 foreground clearance layout");\n  world.dispose();\n});\n'''
marker = '\n\ntest("V9.3 desert fortress reads as a sandwall assault instead of a recolored canyon", () => {'
assert marker in s, 'canyon insertion marker changed'
s = s.replace(marker, insert + marker, 1)
tests.write_text(s)
