from pathlib import Path


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    if old not in text:
        raise SystemExit(f"pattern not found in {path}: {old[:180]!r}")
    path.write_text(text.replace(old, new, 1))

runtime = Path("src/sky/arcade/SkyDancerArcadeRuntime.ts")
replace_once(runtime,
'''export type SkyDancerArcadeEnemyManeuver = "approach" | "close-bank" | "overtake" | "parallel" | "cross-pass";\nexport type SkyDancerArcadeLoadoutReaction = "none" | "fusion-link" | "ripple-shock" | "twin-cannon";\n''',
'''export type SkyDancerArcadeEnemyManeuver = "approach" | "close-bank" | "overtake" | "parallel" | "cross-pass";\nexport type SkyDancerArcadeEnemyAttackPatternV4040 = "snap" | "crossfire" | "spread" | "homing";\nexport type SkyDancerArcadeLoadoutReaction = "none" | "fusion-link" | "ripple-shock" | "twin-cannon";\n''')
replace_once(runtime,
'''  dangerRadius?: number;\n}\n''',
'''  dangerRadius?: number;\n  // V40.40: attack language is presentation metadata only; damage/collision remain unchanged.\n  attackPattern?: SkyDancerArcadeEnemyAttackPatternV4040;\n  dodgeHint?: string;\n  warningIndex?: number;\n  warningCount?: number;\n}\n''')
replace_once(runtime,
'''function skyDancerArcadeEnemyWarningV4034(kind: SkyDancerArcadeEnemyKind | "boss", boss: boolean): number {\n''',
'''export function skyDancerArcadeEnemyAttackPatternV4040(\n  kind: SkyDancerArcadeEnemyKind | "boss",\n  boss: boolean,\n  spreadCount: number,\n  guidance: number,\n): SkyDancerArcadeEnemyAttackPatternV4040 {\n  if (kind === "missile-boat" || guidance >= 1.42) return "homing";\n  if (boss || spreadCount >= 3 || kind === "gunship") return "spread";\n  if (spreadCount >= 2 || kind === "raider" || kind === "striker" || kind === "ace") return "crossfire";\n  return "snap";\n}\n\nexport function skyDancerArcadeEnemyDodgeHintV4040(pattern: SkyDancerArcadeEnemyAttackPatternV4040): string {\n  if (pattern === "homing") return "LATE BREAK · TURBO";\n  if (pattern === "spread") return "CLEAR FAN";\n  if (pattern === "crossfire") return "BREAK SIDE";\n  return "SIDE STEP";\n}\n\nfunction skyDancerArcadeEnemyWarningV4034(kind: SkyDancerArcadeEnemyKind | "boss", boss: boolean): number {\n''')
replace_once(runtime,
'''      const bossSpeedScale = enemy.boss && bossProfile\n        ? bossProfile.projectileSpeedScale[bossIndex] * (reactiveBossPhase?.projectileSpeedScale ?? 1)\n        : 1;\n      const bossSpreadX = enemy.boss && bossProfile ? bossProfile.spreadX[bossIndex] : .2;\n      const bossSpreadY = enemy.boss && bossProfile ? bossProfile.spreadY[bossIndex] : .11;\n      this.projectiles.push({\n''',
'''      const bossSpeedScale = enemy.boss && bossProfile\n        ? bossProfile.projectileSpeedScale[bossIndex] * (reactiveBossPhase?.projectileSpeedScale ?? 1)\n        : 1;\n      const bossSpreadX = enemy.boss && bossProfile ? bossProfile.spreadX[bossIndex] : .2;\n      const bossSpreadY = enemy.boss && bossProfile ? bossProfile.spreadY[bossIndex] : .11;\n      const attackPattern = skyDancerArcadeEnemyAttackPatternV4040(enemy.kind, enemy.boss, spreadCount, guidance);\n      this.projectiles.push({\n''')
replace_once(runtime,
'''        dangerRadius: ENEMY_SHOT_HIT_RADIUS_V4034,\n        dodgeCommitted: false,\n''',
'''        dangerRadius: ENEMY_SHOT_HIT_RADIUS_V4034,\n        attackPattern,\n        dodgeHint: skyDancerArcadeEnemyDodgeHintV4040(attackPattern),\n        warningIndex: index,\n        warningCount: spreadCount,\n        dodgeCommitted: false,\n''')
replace_once(runtime,
'''    if (activeThreats === 0) {\n      this.message = enemy.boss ? "BOSS LOCK · BREAK VECTOR" : "INCOMING · BREAK VECTOR";\n      this.messageTimer = Math.max(this.messageTimer, .72);\n    }\n''',
'''    if (activeThreats === 0) {\n      const previewGuidance = enemy.boss && bossProfile\n        ? (1.02 + enemy.bossPhase * .2) * bossProfile.guidanceScale[bossIndex] * (reactiveBossPhase?.guidanceScale ?? 1)\n        : skyDancerArcadeEnemyWeaponV20(enemy.kind).guidance;\n      const previewPattern = skyDancerArcadeEnemyAttackPatternV4040(enemy.kind, enemy.boss, spreadCount, previewGuidance);\n      this.message = `INCOMING · ${skyDancerArcadeEnemyDodgeHintV4040(previewPattern)}`;\n      this.messageTimer = Math.max(this.messageTimer, .72);\n    }\n''')

webgl = Path("src/sky/arcade/SkyDancerArcadeWebGLDemo.ts")
replace_once(webgl,
'''          trail.renderOrder = 9;\n          mesh.add(glow, core, trail);\n''',
'''          trail.renderOrder = 9;\n          const warningRing = new THREE.Mesh(\n            new THREE.TorusGeometry(.82, .055, 5, 28),\n            new THREE.MeshBasicMaterial({\n              color: 0xffa33d, transparent: true, opacity: .9,\n              blending: THREE.AdditiveBlending, depthWrite: false, depthTest: false, toneMapped: false,\n            }),\n          );\n          warningRing.name = "arcade-enemy-warning-ring-v4040";\n          warningRing.renderOrder = 12;\n          const warningBarA = new THREE.Mesh(\n            new THREE.BoxGeometry(1.5, .055, .045),\n            new THREE.MeshBasicMaterial({\n              color: 0xffa33d, transparent: true, opacity: .86,\n              blending: THREE.AdditiveBlending, depthWrite: false, depthTest: false, toneMapped: false,\n            }),\n          );\n          warningBarA.name = "arcade-enemy-warning-bar-a-v4040";\n          warningBarA.renderOrder = 12;\n          const warningBarB = warningBarA.clone();\n          warningBarB.material = (warningBarA.material as THREE.MeshBasicMaterial).clone();\n          warningBarB.name = "arcade-enemy-warning-bar-b-v4040";\n          mesh.add(glow, core, trail, warningRing, warningBarA, warningBarB);\n''')
replace_once(webgl,
'''        const glow = mesh.getObjectByName("arcade-enemy-projectile-glow-v4035");\n        const core = mesh.getObjectByName("arcade-enemy-projectile-core-v4035");\n        const trail = mesh.getObjectByName("arcade-enemy-projectile-trail-v4035");\n''',
'''        const glow = mesh.getObjectByName("arcade-enemy-projectile-glow-v4035");\n        const core = mesh.getObjectByName("arcade-enemy-projectile-core-v4035");\n        const trail = mesh.getObjectByName("arcade-enemy-projectile-trail-v4035");\n        const warningRing = mesh.getObjectByName("arcade-enemy-warning-ring-v4040");\n        const warningBarA = mesh.getObjectByName("arcade-enemy-warning-bar-a-v4040");\n        const warningBarB = mesh.getObjectByName("arcade-enemy-warning-bar-b-v4040");\n        const attackPattern = projectile.attackPattern ?? "snap";\n        const attackColor = attackPattern === "homing" ? 0xff4fde\n          : attackPattern === "spread" ? 0xff4f62\n            : attackPattern === "crossfire" ? 0xffd65c\n              : 0xffa33d;\n        mesh.material.color.setHex(warning ? attackColor : attackColor);\n''')
replace_once(webgl,
'''        if (trail) {\n          trail.visible = !warning;\n          trail.scale.z = projectile.depth < 9 ? 1.08 : 1;\n          if (trail instanceof THREE.Mesh && trail.material instanceof THREE.MeshBasicMaterial) trail.material.opacity = .38;\n        }\n''',
'''        if (trail) {\n          trail.visible = !warning;\n          trail.scale.z = projectile.depth < 9 ? 1.08 : 1;\n          if (trail instanceof THREE.Mesh && trail.material instanceof THREE.MeshBasicMaterial) {\n            trail.material.opacity = .38;\n            trail.material.color.setHex(attackColor);\n          }\n        }\n        if (glow instanceof THREE.Mesh && glow.material instanceof THREE.MeshBasicMaterial) glow.material.color.setHex(attackColor);\n        if (warningRing) {\n          warningRing.visible = warning;\n          warningRing.rotation.z = attackPattern === "homing" ? Math.PI / 4 : 0;\n          const warningScaleX = attackPattern === "spread" ? 1.65 : attackPattern === "crossfire" ? 1.25 : 1;\n          const warningScaleY = attackPattern === "spread" ? .72 : attackPattern === "homing" ? 1.14 : 1;\n          warningRing.scale.set(warningScaleX, warningScaleY, 1);\n          if (warningRing instanceof THREE.Mesh && warningRing.material instanceof THREE.MeshBasicMaterial) warningRing.material.color.setHex(attackColor);\n        }\n        if (warningBarA && warningBarB) {\n          const barsVisible = warning && attackPattern !== "homing";\n          warningBarA.visible = barsVisible;\n          warningBarB.visible = barsVisible;\n          warningBarA.position.set(attackPattern === "spread" ? -1.05 : -.88, 0, 0);\n          warningBarB.position.set(attackPattern === "spread" ? 1.05 : .88, 0, 0);\n          warningBarA.rotation.z = attackPattern === "crossfire" ? Math.PI / 4 : attackPattern === "spread" ? -.28 : 0;\n          warningBarB.rotation.z = attackPattern === "crossfire" ? -Math.PI / 4 : attackPattern === "spread" ? .28 : 0;\n          for (const bar of [warningBarA, warningBarB]) {\n            if (bar instanceof THREE.Mesh && bar.material instanceof THREE.MeshBasicMaterial) bar.material.color.setHex(attackColor);\n          }\n        }\n''')
# Remove the old one-color assignment that would overwrite V40.40 attack colors.
replace_once(webgl,
'''        mesh.material.color.setHex(warning ? 0xff315e : 0xff5a36);\n        mesh.material.opacity = warning ? .5 : .98;\n''',
'''        mesh.material.opacity = warning ? .46 : .98;\n''')

canvas = Path("src/sky/arcade/SkyDancerArcadeCanvasDemo.ts")
old_warning = '''      if (warning) {\n        const source = this.project(projectile.x, projectile.y, projectile.depth, cssWidth, cssHeight);\n        const pulse = .62 + Math.sin(snapshot.runTimeSeconds * 24 + projectile.id) * .2;\n        context.save();\n        context.strokeStyle = `rgba(255,49,94,${Math.max(.3, pulse)})`;\n        context.lineWidth = 2.2;\n        context.setLineDash([7, 6]);\n        context.beginPath();\n        context.moveTo(source.x, source.y);\n        context.lineTo(projected.x, projected.y);\n        context.stroke();\n        context.setLineDash([]);\n        context.lineWidth = 3;\n        context.beginPath();\n        context.arc(projected.x, projected.y, 18 + pulse * 9, 0, Math.PI * 2);\n        context.stroke();\n        context.restore();\n        continue;\n      }\n'''
new_warning = '''      if (warning) {\n        const source = this.project(projectile.x, projectile.y, projectile.depth, cssWidth, cssHeight);\n        const pulse = .62 + Math.sin(snapshot.runTimeSeconds * 24 + projectile.id) * .2;\n        const pattern = projectile.attackPattern ?? "snap";\n        const color = pattern === "homing" ? "255,79,222"\n          : pattern === "spread" ? "255,79,98"\n            : pattern === "crossfire" ? "255,214,92"\n              : "255,163,61";\n        const ringRadius = 18 + pulse * 9;\n        context.save();\n        context.strokeStyle = `rgba(${color},${Math.max(.36, pulse)})`;\n        context.lineWidth = pattern === "homing" ? 2.8 : 2.2;\n        context.setLineDash(pattern === "homing" ? [3, 4] : [7, 6]);\n        if (pattern === "spread") {\n          const fan = Math.max(24, cssWidth * .055);\n          for (const offset of [-fan, 0, fan]) {\n            context.beginPath();\n            context.moveTo(source.x, source.y);\n            context.lineTo(projected.x + offset, projected.y);\n            context.stroke();\n          }\n        } else {\n          context.beginPath();\n          context.moveTo(source.x, source.y);\n          context.lineTo(projected.x, projected.y);\n          context.stroke();\n        }\n        context.setLineDash([]);\n        if (pattern === "homing") {\n          context.save();\n          context.translate(projected.x, projected.y);\n          context.rotate(Math.PI / 4);\n          context.strokeRect(-ringRadius * .72, -ringRadius * .72, ringRadius * 1.44, ringRadius * 1.44);\n          context.restore();\n          context.beginPath();\n          context.arc(projected.x, projected.y, ringRadius * 1.22, 0, Math.PI * 2);\n          context.stroke();\n        } else if (pattern === "crossfire") {\n          context.beginPath();\n          context.moveTo(projected.x - ringRadius, projected.y - ringRadius);\n          context.lineTo(projected.x + ringRadius, projected.y + ringRadius);\n          context.moveTo(projected.x + ringRadius, projected.y - ringRadius);\n          context.lineTo(projected.x - ringRadius, projected.y + ringRadius);\n          context.stroke();\n        } else if (pattern === "spread") {\n          context.beginPath();\n          context.ellipse(projected.x, projected.y, ringRadius * 1.55, ringRadius * .72, 0, 0, Math.PI * 2);\n          context.stroke();\n        } else {\n          context.beginPath();\n          context.arc(projected.x, projected.y, ringRadius, 0, Math.PI * 2);\n          context.stroke();\n          context.beginPath();\n          context.moveTo(projected.x - ringRadius * 1.55, projected.y);\n          context.lineTo(projected.x - ringRadius * .9, projected.y);\n          context.moveTo(projected.x + ringRadius * .9, projected.y);\n          context.lineTo(projected.x + ringRadius * 1.55, projected.y);\n          context.stroke();\n        }\n        context.restore();\n        continue;\n      }\n'''
replace_once(canvas, old_warning, new_warning)
replace_once(canvas,
'''        context.shadowColor = "rgba(255,82,38,.82)";\n        context.shadowBlur = danger ? 12 : 8;\n''',
'''        const pattern = projectile.attackPattern ?? "snap";\n        const bodyColor = pattern === "homing" ? "255,79,222"\n          : pattern === "spread" ? "255,79,98"\n            : pattern === "crossfire" ? "255,214,92"\n              : "255,106,50";\n        context.shadowColor = `rgba(${bodyColor},.82)`;\n        context.shadowBlur = danger ? 12 : 8;\n''')
replace_once(canvas,
'''        trailGradient.addColorStop(0, danger ? "rgba(255,106,50,.58)" : "rgba(255,106,50,.46)");\n        trailGradient.addColorStop(1, "rgba(255,106,50,0)");\n''',
'''        trailGradient.addColorStop(0, `rgba(${bodyColor},${danger ? ".58" : ".46"})`);\n        trailGradient.addColorStop(1, `rgba(${bodyColor},0)`);\n''')
replace_once(canvas,
'''        context.fillStyle = danger ? "rgba(255,76,38,.17)" : "rgba(255,76,38,.11)";\n''',
'''        context.fillStyle = `rgba(${bodyColor},${danger ? ".17" : ".11"})`;\n''')
replace_once(canvas,
'''        context.fillStyle = "#ff6a32";\n''',
'''        context.fillStyle = `rgb(${bodyColor})`;\n''')

mode = Path("app/SkyDancerArcadeMode.tsx")
replace_once(mode,
'''  const missileDanger = incomingMissiles.some((projectile) => projectile.depth < 17);\n''',
'''  const missileDanger = incomingMissiles.some((projectile) => projectile.depth < 17);\n  const incomingAttackCue = snapshot.projectiles\n    .filter((projectile) => projectile.owner === "enemy" && (projectile.warningSeconds ?? 0) > 0)\n    .sort((a, b) => (a.warningSeconds ?? 99) - (b.warningSeconds ?? 99))[0] ?? null;\n''')
replace_once(mode,
'''        <div className={productStyles.aimGuide} aria-hidden="true"><i /><b /></div>\n''',
'''        <div className={productStyles.aimGuide} aria-hidden="true"><i /><b /></div>\n        {incomingAttackCue?.dodgeHint && (\n          <div className={styles.attackDodgeCueV4040} data-pattern={incomingAttackCue.attackPattern ?? "snap"} aria-live="polite">\n            <small>THREAT READ</small><strong>{incomingAttackCue.dodgeHint}</strong>\n          </div>\n        )}\n''')

css = Path("app/SkyDancerArcadeMode.module.css")
with css.open("a") as handle:
    handle.write(r'''\n\n/* Arcade Run V40.40: enemy attacks teach their dodge rule at a glance. */\n.attackDodgeCueV4040{position:absolute;z-index:12;left:50%;top:57%;transform:translate(-50%,-50%);display:grid;place-items:center;gap:2px;min-width:116px;padding:4px 10px 5px;border:1px solid rgba(255,163,61,.7);border-radius:999px;background:rgba(9,14,27,.58);box-shadow:0 0 18px rgba(255,140,60,.12);pointer-events:none;text-align:center;text-shadow:0 1px 5px rgba(0,0,0,.82)}\n.attackDodgeCueV4040 small{font-size:5px;font-weight:900;letter-spacing:.22em;color:rgba(255,255,255,.62)}\n.attackDodgeCueV4040 strong{font-size:9px;font-weight:1000;letter-spacing:.14em;color:#ffa33d}\n.attackDodgeCueV4040[data-pattern="crossfire"]{border-color:rgba(255,214,92,.72)}.attackDodgeCueV4040[data-pattern="crossfire"] strong{color:#ffd65c}\n.attackDodgeCueV4040[data-pattern="spread"]{border-color:rgba(255,79,98,.78)}.attackDodgeCueV4040[data-pattern="spread"] strong{color:#ff5969}\n.attackDodgeCueV4040[data-pattern="homing"]{border-color:rgba(255,79,222,.8);box-shadow:0 0 20px rgba(255,79,222,.16)}.attackDodgeCueV4040[data-pattern="homing"] strong{color:#ff68e2}\n@media (orientation:landscape) and (max-height:430px){.attackDodgeCueV4040{top:60%;min-width:102px;padding:3px 8px 4px}.attackDodgeCueV4040 small{font-size:4px}.attackDodgeCueV4040 strong{font-size:8px}}\n''')

Path("tests/sky-arcade-v4040-attack-language.test.ts").write_text(r'''import test from "node:test";\nimport assert from "node:assert/strict";\nimport { readFileSync } from "node:fs";\nimport { resolve } from "node:path";\nimport { skyDancerArcadeEnemyAttackPatternV4040, skyDancerArcadeEnemyDodgeHintV4040 } from "../src/sky/arcade/SkyDancerArcadeRuntime";\n\ntest("V40.40 maps enemy pressure to four learnable dodge languages", () => {\n  assert.equal(skyDancerArcadeEnemyAttackPatternV4040("drone", false, 1, .78), "snap");\n  assert.equal(skyDancerArcadeEnemyAttackPatternV4040("raider", false, 2, 1.04), "crossfire");\n  assert.equal(skyDancerArcadeEnemyAttackPatternV4040("gunship", false, 3, 1.2), "spread");\n  assert.equal(skyDancerArcadeEnemyAttackPatternV4040("missile-boat", false, 2, 1.52), "homing");\n  assert.equal(skyDancerArcadeEnemyDodgeHintV4040("snap"), "SIDE STEP");\n  assert.equal(skyDancerArcadeEnemyDodgeHintV4040("homing"), "LATE BREAK · TURBO");\n});\n\ntest("V40.40 carries attack language through WebGL, Canvas and HUD", () => {\n  const webgl = readFileSync(resolve(process.cwd(), "src/sky/arcade/SkyDancerArcadeWebGLDemo.ts"), "utf8");\n  const canvas = readFileSync(resolve(process.cwd(), "src/sky/arcade/SkyDancerArcadeCanvasDemo.ts"), "utf8");\n  const mode = readFileSync(resolve(process.cwd(), "app/SkyDancerArcadeMode.tsx"), "utf8");\n  assert.match(webgl, /arcade-enemy-warning-ring-v4040/);\n  assert.match(webgl, /attackPattern === "homing"/);\n  assert.match(canvas, /pattern === "spread"/);\n  assert.match(canvas, /pattern === "crossfire"/);\n  assert.match(mode, /attackDodgeCueV4040/);\n  assert.match(mode, /incomingAttackCue\.dodgeHint/);\n});\n''')
