from pathlib import Path

helper = Path('src/sky/arcade/SkyDancerArcadeV122EncounterContinuity.ts')
helper.write_text('''export type SkyDancerArcadeV122FlowSign = -1 | 0 | 1;\n\nexport interface SkyDancerArcadeV122ContinuityInput {\n  playerX: number;\n  playerVX: number;\n  survivorXs: readonly number[];\n  phaseIndex: number;\n}\n\nexport interface SkyDancerArcadeV122Continuity {\n  breakSign: SkyDancerArcadeV122FlowSign;\n  entrySign: SkyDancerArcadeV122FlowSign;\n  survivorCount: number;\n  survivorCentroidX: number;\n  lateralBias: number;\n  label: string;\n}\n\nfunction flowSign(value: number, deadzone: number): SkyDancerArcadeV122FlowSign {\n  if (value > deadzone) return 1;\n  if (value < -deadzone) return -1;\n  return 0;\n}\n\nfunction clamp(value: number, min: number, max: number): number {\n  return Math.max(min, Math.min(max, value));\n}\n\n/**\n * V12.2 keeps a multi-phase encounter spatially continuous. Player momentum owns\n * the primary read; when the player is centered, surviving enemies tell the next\n * reinforcement which empty side of the arena should be filled.\n */\nexport function skyDancerArcadeV122EncounterContinuity(\n  input: SkyDancerArcadeV122ContinuityInput,\n): SkyDancerArcadeV122Continuity {\n  const survivorCount = input.survivorXs.length;\n  const survivorCentroidX = survivorCount > 0\n    ? input.survivorXs.reduce((sum, x) => sum + x, 0) / survivorCount\n    : 0;\n  const velocityBreak = flowSign(input.playerVX, .32);\n  const positionBreak = flowSign(input.playerX, .84);\n  const breakSign = velocityBreak !== 0 ? velocityBreak : positionBreak;\n  const survivorSide = flowSign(survivorCentroidX, .28);\n  let entrySign: SkyDancerArcadeV122FlowSign = 0;\n  if (input.phaseIndex > 0) {\n    if (breakSign !== 0) entrySign = breakSign;\n    else if (survivorSide !== 0) entrySign = survivorSide === 1 ? -1 : 1;\n    else entrySign = input.phaseIndex % 2 === 1 ? 1 : -1;\n  }\n  const lateralBias = entrySign === 0\n    ? 0\n    : entrySign * clamp(.34 + input.phaseIndex * .16 + Math.min(4, survivorCount) * .035, .34, .92);\n  const side = entrySign > 0 ? 'R' : entrySign < 0 ? 'L' : 'HOLD';\n  const action = breakSign !== 0 ? 'BLOCK' : survivorSide !== 0 ? 'FILL' : 'FLOW';\n  return {\n    breakSign,\n    entrySign,\n    survivorCount,\n    survivorCentroidX,\n    lateralBias,\n    label: `${action} ${side} · CARRY ${survivorCount}`,\n  };\n}\n''')

runtime = Path('src/sky/arcade/SkyDancerArcadeRuntime.ts')
s = runtime.read_text()

anchor = '''import {\n  skyDancerArcadeV121EncounterGrammar,\n  type SkyDancerArcadeV121EncounterGrammar,\n  type SkyDancerArcadeV121EncounterPhase,\n} from "./SkyDancerArcadeV121EncounterGrammar";\n'''
insert = anchor + '''import {\n  skyDancerArcadeV122EncounterContinuity,\n  type SkyDancerArcadeV122FlowSign,\n} from "./SkyDancerArcadeV122EncounterContinuity";\n'''
if anchor not in s: raise SystemExit('runtime import anchor missing')
s = s.replace(anchor, insert, 1)

anchor = '''  encounterGrammarPhaseCount: number;\n  encounterGrammarSerial: number;\n  bossKills: number;\n'''
replace = '''  encounterGrammarPhaseCount: number;\n  encounterGrammarSerial: number;\n  encounterContinuityLabel: string;\n  encounterContinuityBreakSign: SkyDancerArcadeV122FlowSign;\n  encounterContinuityEntrySign: SkyDancerArcadeV122FlowSign;\n  encounterContinuitySurvivors: number;\n  encounterContinuityLateralBias: number;\n  encounterContinuitySerial: number;\n  bossKills: number;\n'''
if anchor not in s: raise SystemExit('snapshot interface anchor missing')
s = s.replace(anchor, replace, 1)

anchor = '''  private encounterGrammarSerial = 0;\n  private encounterGrammarCadenceScale = 1;\n  private encounterPhaseQueue: ArcadeV121QueuedPhase[] = [];\n'''
replace = '''  private encounterGrammarSerial = 0;\n  private encounterGrammarCadenceScale = 1;\n  private encounterContinuityLabel = "FLOW HOLD · CARRY 0";\n  private encounterContinuityBreakSign: SkyDancerArcadeV122FlowSign = 0;\n  private encounterContinuityEntrySign: SkyDancerArcadeV122FlowSign = 0;\n  private encounterContinuitySurvivors = 0;\n  private encounterContinuityLateralBias = 0;\n  private encounterContinuitySerial = 0;\n  private encounterPhaseQueue: ArcadeV121QueuedPhase[] = [];\n'''
if anchor not in s: raise SystemExit('private continuity anchor missing')
s = s.replace(anchor, replace, 1)

anchor = '''    this.encounterGrammarPhaseCount = 1;\n    this.encounterGrammarCadenceScale = 1;\n    this.encounterPhaseQueue = [];\n'''
replace = '''    this.encounterGrammarPhaseCount = 1;\n    this.encounterGrammarCadenceScale = 1;\n    this.encounterContinuityLabel = "FLOW HOLD · CARRY 0";\n    this.encounterContinuityBreakSign = 0;\n    this.encounterContinuityEntrySign = 0;\n    this.encounterContinuitySurvivors = 0;\n    this.encounterContinuityLateralBias = 0;\n    this.encounterContinuitySerial = 0;\n    this.encounterPhaseQueue = [];\n'''
if anchor not in s: raise SystemExit('reset continuity anchor missing')
s = s.replace(anchor, replace, 1)

anchor = '''    this.encounterGrammarPhaseLabel = phase.label;\n    this.encounterGrammarPhaseIndex = phaseIndex + 1;\n    this.encounterGrammarPhaseCount = grammar.phases.length;\n\n    const progress = clamp(this.stageTime / this.stage.durationSeconds, 0, 1);\n'''
replace = '''    this.encounterGrammarPhaseLabel = phase.label;\n    this.encounterGrammarPhaseIndex = phaseIndex + 1;\n    this.encounterGrammarPhaseCount = grammar.phases.length;\n    const carryoverEnemies = this.enemies.filter((enemy) => enemy.alive && !enemy.boss);\n    const continuity = skyDancerArcadeV122EncounterContinuity({\n      playerX: this.playerX,\n      playerVX: this.playerVX,\n      survivorXs: carryoverEnemies.map((enemy) => enemy.x),\n      phaseIndex,\n    });\n    this.encounterContinuityLabel = continuity.label;\n    this.encounterContinuityBreakSign = continuity.breakSign;\n    this.encounterContinuityEntrySign = continuity.entrySign;\n    this.encounterContinuitySurvivors = continuity.survivorCount;\n    this.encounterContinuityLateralBias = continuity.lateralBias;\n    this.encounterContinuitySerial += 1;\n\n    const progress = clamp(this.stageTime / this.stage.durationSeconds, 0, 1);\n'''
if anchor not in s: raise SystemExit('phase continuity anchor missing')
s = s.replace(anchor, replace, 1)

anchor = '''      const sign = Math.abs(formationX) > 0.18 ? Math.sign(formationX) : (index + phaseIndex) % 2 === 0 ? 1 : -1;\n      const x = maneuver === "overtake"\n        ? sign * 1.9\n        : maneuver === "cross-pass"\n          ? clamp(formationX + sign * .18, -ENEMY_X_LIMIT, ENEMY_X_LIMIT)\n          : formationX;\n      const y = maneuver === "overtake" ? clamp(formationY * .34, -.62, .62) : formationY;\n'''
replace = '''      const formationSign = Math.abs(formationX) > 0.18 ? Math.sign(formationX) : (index + phaseIndex) % 2 === 0 ? 1 : -1;\n      const sign = maneuver === "overtake" && phaseIndex > 0 && continuity.entrySign !== 0\n        ? continuity.entrySign\n        : formationSign;\n      const flowBias = phaseIndex > 0 && maneuver !== "overtake" ? continuity.lateralBias : 0;\n      const x = maneuver === "overtake"\n        ? sign * 1.9\n        : maneuver === "cross-pass"\n          ? clamp(formationX + sign * .18 + flowBias, -ENEMY_X_LIMIT, ENEMY_X_LIMIT)\n          : clamp(formationX + flowBias, -ENEMY_X_LIMIT, ENEMY_X_LIMIT);\n      const y = maneuver === "overtake" ? clamp(formationY * .34, -.62, .62) : formationY;\n'''
if anchor not in s: raise SystemExit('spawn flow anchor missing')
s = s.replace(anchor, replace, 1)

anchor = '''      encounterGrammarPhaseCount: this.encounterGrammarPhaseCount,\n      encounterGrammarSerial: this.encounterGrammarSerial,\n      bossKills: this.bossKills,\n'''
replace = '''      encounterGrammarPhaseCount: this.encounterGrammarPhaseCount,\n      encounterGrammarSerial: this.encounterGrammarSerial,\n      encounterContinuityLabel: this.encounterContinuityLabel,\n      encounterContinuityBreakSign: this.encounterContinuityBreakSign,\n      encounterContinuityEntrySign: this.encounterContinuityEntrySign,\n      encounterContinuitySurvivors: this.encounterContinuitySurvivors,\n      encounterContinuityLateralBias: this.encounterContinuityLateralBias,\n      encounterContinuitySerial: this.encounterContinuitySerial,\n      bossKills: this.bossKills,\n'''
if anchor not in s: raise SystemExit('snapshot output anchor missing')
s = s.replace(anchor, replace, 1)

anchor = '''  advanceV121EncounterForTests(): boolean {\n    const next = this.encounterPhaseQueue[0];\n    if (!next) return false;\n    this.stageTime = Math.max(this.stageTime, next.at);\n    this.distance = this.stageTime * this.stage.courseSpeed;\n    this.updateV121EncounterQueue();\n    return true;\n  }\n\n  /** Deterministic V11.8 hooks for loadout combat regression tests. */\n'''
replace = '''  advanceV121EncounterForTests(): boolean {\n    const next = this.encounterPhaseQueue[0];\n    if (!next) return false;\n    this.stageTime = Math.max(this.stageTime, next.at);\n    this.distance = this.stageTime * this.stage.courseSpeed;\n    this.updateV121EncounterQueue();\n    return true;\n  }\n\n  setV122PlayerFlowForTests(x: number, vx: number): void {\n    this.playerX = clamp(x, -PLAYER_X_LIMIT, PLAYER_X_LIMIT);\n    this.playerVX = clamp(vx, -PLAYER_TURBO_SPEED_X, PLAYER_TURBO_SPEED_X);\n  }\n\n  /** Deterministic V11.8 hooks for loadout combat regression tests. */\n'''
if anchor not in s: raise SystemExit('test hook anchor missing')
s = s.replace(anchor, replace, 1)
runtime.write_text(s)

mode = Path('app/SkyDancerArcadeMode.tsx')
m = mode.read_text()
anchor = '''          <em className={productStyles.v121GrammarLine}>ENCOUNTER · {snapshot.encounterGrammarLabel} · {snapshot.encounterGrammarPhaseLabel} {snapshot.encounterGrammarPhaseIndex}/{snapshot.encounterGrammarPhaseCount}</em>\n'''
replace = '''          <em className={productStyles.v121GrammarLine}>ENCOUNTER · {snapshot.encounterGrammarLabel} · {snapshot.encounterGrammarPhaseLabel} {snapshot.encounterGrammarPhaseIndex}/{snapshot.encounterGrammarPhaseCount} · {snapshot.encounterContinuityLabel}</em>\n'''
if anchor not in m: raise SystemExit('HUD encounter anchor missing')
m = m.replace(anchor, replace, 1)
m = m.replace('`3D FLIGHT · V12.1 · ${snapshot.paintScheme.toUpperCase()} · ${snapshot.loadout.toUpperCase()}`', '`3D FLIGHT · V12.2 · ${snapshot.paintScheme.toUpperCase()} · ${snapshot.loadout.toUpperCase()}`', 1)
m = m.replace('`COMPATIBILITY · CANVAS · V12.1 · ${snapshot.loadout.toUpperCase()}`', '`COMPATIBILITY · CANVAS · V12.2 · ${snapshot.loadout.toUpperCase()}`', 1)
mode.write_text(m)

tests = Path('tests/sky-arcade-run.test.ts')
t = tests.read_text()
anchor = 'import { skyDancerArcadeV121EncounterGrammar } from "../src/sky/arcade/SkyDancerArcadeV121EncounterGrammar";\n'
insert = anchor + 'import { skyDancerArcadeV122EncounterContinuity } from "../src/sky/arcade/SkyDancerArcadeV122EncounterContinuity";\n'
if anchor not in t: raise SystemExit('test import anchor missing')
t = t.replace(anchor, insert, 1)
t += '''\n\ntest("V12.2 continuity blocks the player break lane and fills the empty side", () => {\n  const rightBreak = skyDancerArcadeV122EncounterContinuity({ playerX: .3, playerVX: 1.2, survivorXs: [-.4, .2], phaseIndex: 1 });\n  assert.equal(rightBreak.breakSign, 1);\n  assert.equal(rightBreak.entrySign, 1);\n  assert.ok(rightBreak.lateralBias > 0);\n  assert.match(rightBreak.label, /BLOCK R/);\n\n  const fillLeft = skyDancerArcadeV122EncounterContinuity({ playerX: 0, playerVX: 0, survivorXs: [.8, 1.2], phaseIndex: 1 });\n  assert.equal(fillLeft.breakSign, 0);\n  assert.equal(fillLeft.entrySign, -1);\n  assert.ok(fillLeft.lateralBias < 0);\n  assert.match(fillLeft.label, /FILL L/);\n});\n\ntest("V12.2 Encounter Continuity carries survivor IDs and steers each reinforcement phase", () => {\n  const runtime = new SkyDancerArcadeRuntime({ mode: "stage-practice", difficulty: "normal", startStageId: "dawn-city", seed: 122 });\n  runtime.setV12DirectorSignalsForTests(.1, 1.8, .1);\n  runtime.setV122PlayerFlowForTests(1.1, 1.35);\n  runtime.spawnV12EncounterForTests();\n  const first = runtime.getSnapshot();\n  assert.equal(first.combatDirectorMode, "hunter-sweep");\n  const firstIds = new Set(first.enemies.map((enemy) => enemy.id));\n  assert.ok(firstIds.size > 0);\n\n  assert.equal(runtime.advanceV121EncounterForTests(), true);\n  const second = runtime.getSnapshot();\n  assert.equal(second.encounterGrammarPhaseIndex, 2);\n  assert.equal(second.encounterContinuityBreakSign, 1);\n  assert.equal(second.encounterContinuityEntrySign, 1);\n  assert.ok(second.encounterContinuitySurvivors >= firstIds.size);\n  assert.ok([...firstIds].every((id) => second.enemies.some((enemy) => enemy.id === id)), "phase-one enemies must survive into phase two");\n  const secondReinforcements = second.enemies.filter((enemy) => !firstIds.has(enemy.id));\n  assert.ok(secondReinforcements.length > 0);\n  assert.ok(secondReinforcements.reduce((sum, enemy) => sum + enemy.x, 0) / secondReinforcements.length > .05, "right break should bias the cut to the right lane");\n\n  const secondIds = new Set(second.enemies.map((enemy) => enemy.id));\n  runtime.setV122PlayerFlowForTests(-1.1, -1.35);\n  assert.equal(runtime.advanceV121EncounterForTests(), true);\n  const third = runtime.getSnapshot();\n  assert.equal(third.encounterGrammarPhaseIndex, 3);\n  assert.equal(third.encounterContinuityBreakSign, -1);\n  assert.equal(third.encounterContinuityEntrySign, -1);\n  assert.ok([...secondIds].every((id) => third.enemies.some((enemy) => enemy.id === id)), "phase-two enemies must carry into the finishing phase");\n  const thirdReinforcements = third.enemies.filter((enemy) => !secondIds.has(enemy.id));\n  assert.ok(thirdReinforcements.length > 0);\n  assert.ok(thirdReinforcements.reduce((sum, enemy) => sum + enemy.x, 0) / thirdReinforcements.length < -.05, "left break should pull the finishing cut into the left lane");\n});\n'''
tests.write_text(t)
